# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designDrawSchemesTwo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowDrawSchemesTwo(object):
    def setupUi(self, WindowDrawSchemesTwo):
        WindowDrawSchemesTwo.setObjectName("WindowDrawSchemesTwo")
        WindowDrawSchemesTwo.setEnabled(True)
        WindowDrawSchemesTwo.resize(947, 661)
        font = QtGui.QFont()
        font.setFamily("Arial")
        WindowDrawSchemesTwo.setFont(font)
        WindowDrawSchemesTwo.setFocusPolicy(QtCore.Qt.NoFocus)
        WindowDrawSchemesTwo.setToolTip("")
        WindowDrawSchemesTwo.setStyleSheet("QMainWindow {\n"
"    background-color: white\n"
"}\n"
"QScrollBar:vertical {              \n"
"    background: #e5e5ea;\n"
"    border-radius: 3;\n"
"    border: none;\n"
"    max-width: 8px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #196dff;\n"
"    border-radius: 3;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #3b83ff; \n"
"    min-height: 0px;\n"
"    border-radius: 3;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: #e5e5ea;\n"
"    border: none;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background: transparent;\n"
"    border-radius: 6;\n"
"    border: none;\n"
"    outline:0px;\n"
"    selection-background-color: white;\n"
"    selection-color: #196dff;\n"
"    padding: 8 0 8 0;\n"
"}")
        WindowDrawSchemesTwo.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(WindowDrawSchemesTwo)
        self.centralwidget.setStyleSheet("background-color: #fff;")
        self.centralwidget.setObjectName("centralwidget")
        self.inputName_other = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName_other.setGeometry(QtCore.QRect(398, 50, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.inputName_other.setFont(font)
        self.inputName_other.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputName_other.setInputMask("")
        self.inputName_other.setText("")
        self.inputName_other.setPlaceholderText("")
        self.inputName_other.setObjectName("inputName_other")
        self.textConsoleDraw = QtWidgets.QTextBrowser(self.centralwidget)
        self.textConsoleDraw.setEnabled(True)
        self.textConsoleDraw.setGeometry(QtCore.QRect(561, 50, 371, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textConsoleDraw.setFont(font)
        self.textConsoleDraw.setStyleSheet("QTextBrowser{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding: 8 4 8 8;\n"
"}\n"
"")
        self.textConsoleDraw.setObjectName("textConsoleDraw")
        self.btnDraw = QtWidgets.QPushButton(self.centralwidget)
        self.btnDraw.setGeometry(QtCore.QRect(198, 250, 317, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnDraw.setFont(font)
        self.btnDraw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDraw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(60,178,0);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(60,178,0, 0.85); \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(255, 255, 255, 0.7);\n"
"    border-radius: 12;\n"
"}")
        self.btnDraw.setObjectName("btnDraw")
        self.inputPower_invertor = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPower_invertor.setGeometry(QtCore.QRect(197, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.inputPower_invertor.setFont(font)
        self.inputPower_invertor.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputPower_invertor.setInputMask("")
        self.inputPower_invertor.setText("")
        self.inputPower_invertor.setPlaceholderText("")
        self.inputPower_invertor.setObjectName("inputPower_invertor")
        self.inputAmperage_invertor = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAmperage_invertor.setGeometry(QtCore.QRect(197, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.inputAmperage_invertor.setFont(font)
        self.inputAmperage_invertor.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputAmperage_invertor.setInputMask("")
        self.inputAmperage_invertor.setText("")
        self.inputAmperage_invertor.setPlaceholderText("")
        self.inputAmperage_invertor.setObjectName("inputAmperage_invertor")
        self.checkUse_threePhase = QtWidgets.QCheckBox(self.centralwidget)
        self.checkUse_threePhase.setGeometry(QtCore.QRect(198, 215, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkUse_threePhase.setFont(font)
        self.checkUse_threePhase.setObjectName("checkUse_threePhase")
        self.checkUse_yzip = QtWidgets.QCheckBox(self.centralwidget)
        self.checkUse_yzip.setGeometry(QtCore.QRect(20, 215, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkUse_yzip.setFont(font)
        self.checkUse_yzip.setObjectName("checkUse_yzip")
        self.checkUse_counter = QtWidgets.QCheckBox(self.centralwidget)
        self.checkUse_counter.setGeometry(QtCore.QRect(100, 215, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkUse_counter.setFont(font)
        self.checkUse_counter.setObjectName("checkUse_counter")
        self.inputName_invertor = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName_invertor.setGeometry(QtCore.QRect(197, 50, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.inputName_invertor.setFont(font)
        self.inputName_invertor.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputName_invertor.setInputMask("")
        self.inputName_invertor.setText("")
        self.inputName_invertor.setPlaceholderText("")
        self.inputName_invertor.setObjectName("inputName_invertor")
        self.inputPower_other = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPower_other.setGeometry(QtCore.QRect(398, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.inputPower_other.setFont(font)
        self.inputPower_other.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputPower_other.setInputMask("")
        self.inputPower_other.setText("")
        self.inputPower_other.setPlaceholderText("")
        self.inputPower_other.setObjectName("inputPower_other")
        self.inputAmperage_other = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAmperage_other.setGeometry(QtCore.QRect(398, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.inputAmperage_other.setFont(font)
        self.inputAmperage_other.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputAmperage_other.setInputMask("")
        self.inputAmperage_other.setText("")
        self.inputAmperage_other.setPlaceholderText("")
        self.inputAmperage_other.setObjectName("inputAmperage_other")
        self.inputType_other = QtWidgets.QLineEdit(self.centralwidget)
        self.inputType_other.setGeometry(QtCore.QRect(398, 210, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.inputType_other.setFont(font)
        self.inputType_other.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputType_other.setInputMask("")
        self.inputType_other.setText("")
        self.inputType_other.setPlaceholderText("")
        self.inputType_other.setObjectName("inputType_other")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(197, 14, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setEnabled(True)
        self.label_10.setGeometry(QtCore.QRect(398, 15, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setEnabled(True)
        self.label_11.setGeometry(QtCore.QRect(20, 55, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setEnabled(True)
        self.label_12.setGeometry(QtCore.QRect(20, 95, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.spinBox_countInvertor = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_countInvertor.setGeometry(QtCore.QRect(197, 90, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_countInvertor.setFont(font)
        self.spinBox_countInvertor.setStyleSheet("QSpinBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QSpinBox:up-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-top-right-radius: 6;\n"
"    border: none;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"QSpinBox:down-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-bottom-right-radius: 6;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"\n"
"}")
        self.spinBox_countInvertor.setObjectName("spinBox_countInvertor")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setEnabled(True)
        self.label_13.setGeometry(QtCore.QRect(20, 136, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setEnabled(True)
        self.label_14.setGeometry(QtCore.QRect(20, 175, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setEnabled(True)
        self.label_15.setGeometry(QtCore.QRect(361, 216, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.spinBox_countOther = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_countOther.setGeometry(QtCore.QRect(398, 90, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_countOther.setFont(font)
        self.spinBox_countOther.setStyleSheet("QSpinBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QSpinBox:up-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-top-right-radius: 6;\n"
"    border: none;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"QSpinBox:down-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-bottom-right-radius: 6;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"\n"
"}")
        self.spinBox_countOther.setObjectName("spinBox_countOther")
        self.btnOpen_otherParams = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpen_otherParams.setGeometry(QtCore.QRect(20, 250, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnOpen_otherParams.setFont(font)
        self.btnOpen_otherParams.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOpen_otherParams.setStyleSheet("QPushButton{\n"
"    background-color: #196dff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #3b83ff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(255, 255, 255, 0.7);\n"
"    border-radius: 12;\n"
"}")
        self.btnOpen_otherParams.setObjectName("btnOpen_otherParams")
        self.inputParam1_invertor = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam1_invertor.setGeometry(QtCore.QRect(197, 370, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam1_invertor.setFont(font)
        self.inputParam1_invertor.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam1_invertor.setInputMask("")
        self.inputParam1_invertor.setText("")
        self.inputParam1_invertor.setPlaceholderText("")
        self.inputParam1_invertor.setObjectName("inputParam1_invertor")
        self.inputParam2_invertor = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam2_invertor.setGeometry(QtCore.QRect(197, 400, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam2_invertor.setFont(font)
        self.inputParam2_invertor.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam2_invertor.setInputMask("")
        self.inputParam2_invertor.setText("")
        self.inputParam2_invertor.setPlaceholderText("")
        self.inputParam2_invertor.setObjectName("inputParam2_invertor")
        self.inputParam2_other = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam2_other.setGeometry(QtCore.QRect(398, 400, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam2_other.setFont(font)
        self.inputParam2_other.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam2_other.setInputMask("")
        self.inputParam2_other.setText("")
        self.inputParam2_other.setPlaceholderText("")
        self.inputParam2_other.setObjectName("inputParam2_other")
        self.inputParam1_other = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam1_other.setGeometry(QtCore.QRect(398, 370, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam1_other.setFont(font)
        self.inputParam1_other.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam1_other.setInputMask("")
        self.inputParam1_other.setText("")
        self.inputParam1_other.setPlaceholderText("")
        self.inputParam1_other.setObjectName("inputParam1_other")
        self.inputParam6_invertor = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam6_invertor.setGeometry(QtCore.QRect(197, 470, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam6_invertor.setFont(font)
        self.inputParam6_invertor.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam6_invertor.setInputMask("")
        self.inputParam6_invertor.setText("")
        self.inputParam6_invertor.setPlaceholderText("")
        self.inputParam6_invertor.setObjectName("inputParam6_invertor")
        self.inputParam6_other = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam6_other.setGeometry(QtCore.QRect(398, 470, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam6_other.setFont(font)
        self.inputParam6_other.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam6_other.setInputMask("")
        self.inputParam6_other.setText("")
        self.inputParam6_other.setPlaceholderText("")
        self.inputParam6_other.setObjectName("inputParam6_other")
        self.inputParam7_invertor = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam7_invertor.setGeometry(QtCore.QRect(197, 500, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam7_invertor.setFont(font)
        self.inputParam7_invertor.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam7_invertor.setInputMask("")
        self.inputParam7_invertor.setText("")
        self.inputParam7_invertor.setPlaceholderText("")
        self.inputParam7_invertor.setObjectName("inputParam7_invertor")
        self.inputParam7_other = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam7_other.setGeometry(QtCore.QRect(398, 500, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam7_other.setFont(font)
        self.inputParam7_other.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam7_other.setInputMask("")
        self.inputParam7_other.setText("")
        self.inputParam7_other.setPlaceholderText("")
        self.inputParam7_other.setObjectName("inputParam7_other")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setEnabled(True)
        self.label_16.setGeometry(QtCore.QRect(561, 340, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.inputParam2_yzip = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam2_yzip.setGeometry(QtCore.QRect(561, 370, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam2_yzip.setFont(font)
        self.inputParam2_yzip.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam2_yzip.setInputMask("")
        self.inputParam2_yzip.setText("")
        self.inputParam2_yzip.setPlaceholderText("")
        self.inputParam2_yzip.setObjectName("inputParam2_yzip")
        self.inputParam1_yzip = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam1_yzip.setGeometry(QtCore.QRect(561, 470, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam1_yzip.setFont(font)
        self.inputParam1_yzip.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam1_yzip.setInputMask("")
        self.inputParam1_yzip.setText("")
        self.inputParam1_yzip.setPlaceholderText("")
        self.inputParam1_yzip.setObjectName("inputParam1_yzip")
        self.inputParam3_yzip = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam3_yzip.setGeometry(QtCore.QRect(561, 400, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam3_yzip.setFont(font)
        self.inputParam3_yzip.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam3_yzip.setInputMask("")
        self.inputParam3_yzip.setText("")
        self.inputParam3_yzip.setPlaceholderText("")
        self.inputParam3_yzip.setObjectName("inputParam3_yzip")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setEnabled(True)
        self.label_17.setGeometry(QtCore.QRect(20, 370, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setEnabled(True)
        self.label_18.setGeometry(QtCore.QRect(20, 401, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setEnabled(True)
        self.label_22.setGeometry(QtCore.QRect(20, 470, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setEnabled(True)
        self.label_23.setGeometry(QtCore.QRect(20, 499, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setEnabled(True)
        self.label_24.setGeometry(QtCore.QRect(20, 335, 311, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.inputParam2_out = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam2_out.setGeometry(QtCore.QRect(751, 470, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam2_out.setFont(font)
        self.inputParam2_out.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam2_out.setInputMask("")
        self.inputParam2_out.setText("")
        self.inputParam2_out.setPlaceholderText("")
        self.inputParam2_out.setObjectName("inputParam2_out")
        self.inputParam4_out = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam4_out.setGeometry(QtCore.QRect(751, 500, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam4_out.setFont(font)
        self.inputParam4_out.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam4_out.setInputMask("")
        self.inputParam4_out.setText("")
        self.inputParam4_out.setPlaceholderText("")
        self.inputParam4_out.setObjectName("inputParam4_out")
        self.inputParam3_out = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam3_out.setGeometry(QtCore.QRect(751, 530, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam3_out.setFont(font)
        self.inputParam3_out.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam3_out.setInputMask("")
        self.inputParam3_out.setText("")
        self.inputParam3_out.setPlaceholderText("")
        self.inputParam3_out.setObjectName("inputParam3_out")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setEnabled(True)
        self.label_25.setGeometry(QtCore.QRect(751, 340, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.checkRedLineInvertor = QtWidgets.QCheckBox(self.centralwidget)
        self.checkRedLineInvertor.setGeometry(QtCore.QRect(229, 530, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkRedLineInvertor.setFont(font)
        self.checkRedLineInvertor.setStyleSheet("QCheckBox{\n"
"    background-color:red; \n"
"    border: none;\n"
"    padding-left: 3.5;\n"
"}")
        self.checkRedLineInvertor.setText("")
        self.checkRedLineInvertor.setObjectName("checkRedLineInvertor")
        self.checkBlueLineInvertor = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBlueLineInvertor.setGeometry(QtCore.QRect(260, 530, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBlueLineInvertor.setFont(font)
        self.checkBlueLineInvertor.setStyleSheet("QCheckBox{\n"
"    background-color:blue; \n"
"    border: none;\n"
"    padding-left: 3.5;\n"
"}")
        self.checkBlueLineInvertor.setText("")
        self.checkBlueLineInvertor.setObjectName("checkBlueLineInvertor")
        self.checkGreenLineInvertor = QtWidgets.QCheckBox(self.centralwidget)
        self.checkGreenLineInvertor.setGeometry(QtCore.QRect(291, 530, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkGreenLineInvertor.setFont(font)
        self.checkGreenLineInvertor.setStyleSheet("QCheckBox{\n"
"    background-color:lightgreen; \n"
"    border: none;\n"
"    padding-left: 3.5;\n"
"}")
        self.checkGreenLineInvertor.setText("")
        self.checkGreenLineInvertor.setObjectName("checkGreenLineInvertor")
        self.checkBlackLineInvertor = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBlackLineInvertor.setGeometry(QtCore.QRect(322, 530, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBlackLineInvertor.setFont(font)
        self.checkBlackLineInvertor.setStyleSheet("QCheckBox{\n"
"    background-color:black; \n"
"    border-top-right-radius: 5;\n"
"    border-bottom-right-radius: 5;\n"
"    border: none;\n"
"    padding-left: 3.5;\n"
"}")
        self.checkBlackLineInvertor.setText("")
        self.checkBlackLineInvertor.setObjectName("checkBlackLineInvertor")
        self.checkBlueLineOther = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBlueLineOther.setGeometry(QtCore.QRect(460, 530, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBlueLineOther.setFont(font)
        self.checkBlueLineOther.setStyleSheet("QCheckBox{\n"
"    background-color:blue; \n"
"    border: none;\n"
"    padding-left: 3.5;\n"
"}")
        self.checkBlueLineOther.setText("")
        self.checkBlueLineOther.setObjectName("checkBlueLineOther")
        self.checkRedLineOther = QtWidgets.QCheckBox(self.centralwidget)
        self.checkRedLineOther.setGeometry(QtCore.QRect(429, 530, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkRedLineOther.setFont(font)
        self.checkRedLineOther.setStyleSheet("QCheckBox{\n"
"    background-color:red; \n"
"    border: none;\n"
"    padding-left: 3.5;\n"
"}")
        self.checkRedLineOther.setText("")
        self.checkRedLineOther.setObjectName("checkRedLineOther")
        self.checkBlackLineOther = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBlackLineOther.setGeometry(QtCore.QRect(522, 530, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBlackLineOther.setFont(font)
        self.checkBlackLineOther.setStyleSheet("QCheckBox{\n"
"    background-color:black; \n"
"    border-top-right-radius: 5;\n"
"    border-bottom-right-radius: 5;\n"
"    border: none;\n"
"    padding-left: 3.5;\n"
"}")
        self.checkBlackLineOther.setText("")
        self.checkBlackLineOther.setObjectName("checkBlackLineOther")
        self.checkGreenLineOther = QtWidgets.QCheckBox(self.centralwidget)
        self.checkGreenLineOther.setGeometry(QtCore.QRect(491, 530, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkGreenLineOther.setFont(font)
        self.checkGreenLineOther.setStyleSheet("QCheckBox{\n"
"    background-color:lightgreen; \n"
"    border: none;\n"
"    padding-left: 3.5;\n"
"}")
        self.checkGreenLineOther.setText("")
        self.checkGreenLineOther.setObjectName("checkGreenLineOther")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setEnabled(True)
        self.label_26.setGeometry(QtCore.QRect(20, 556, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.checkBlueSwitchOther = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBlueSwitchOther.setGeometry(QtCore.QRect(462, 555, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBlueSwitchOther.setFont(font)
        self.checkBlueSwitchOther.setStyleSheet("QCheckBox{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    border-radius: 5;\n"
"    border: none;\n"
"    padding: 2;\n"
"}")
        self.checkBlueSwitchOther.setText("")
        self.checkBlueSwitchOther.setObjectName("checkBlueSwitchOther")
        self.checkRedSwitchOther = QtWidgets.QCheckBox(self.centralwidget)
        self.checkRedSwitchOther.setGeometry(QtCore.QRect(431, 555, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkRedSwitchOther.setFont(font)
        self.checkRedSwitchOther.setStyleSheet("QCheckBox{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    border-radius: 5;\n"
"    border: none;\n"
"    padding: 2;\n"
"}")
        self.checkRedSwitchOther.setText("")
        self.checkRedSwitchOther.setObjectName("checkRedSwitchOther")
        self.checkBlueSwitchInvertor = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBlueSwitchInvertor.setGeometry(QtCore.QRect(262, 555, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBlueSwitchInvertor.setFont(font)
        self.checkBlueSwitchInvertor.setStyleSheet("QCheckBox{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    border-radius: 5;\n"
"    border: none;\n"
"    padding: 2;\n"
"}")
        self.checkBlueSwitchInvertor.setText("")
        self.checkBlueSwitchInvertor.setObjectName("checkBlueSwitchInvertor")
        self.checkGreenSwitchOther = QtWidgets.QCheckBox(self.centralwidget)
        self.checkGreenSwitchOther.setGeometry(QtCore.QRect(493, 555, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkGreenSwitchOther.setFont(font)
        self.checkGreenSwitchOther.setStyleSheet("QCheckBox{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    border-radius: 5;\n"
"    border: none;\n"
"    padding: 2;\n"
"}")
        self.checkGreenSwitchOther.setText("")
        self.checkGreenSwitchOther.setObjectName("checkGreenSwitchOther")
        self.checkRedSwitchInvertor = QtWidgets.QCheckBox(self.centralwidget)
        self.checkRedSwitchInvertor.setGeometry(QtCore.QRect(231, 555, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkRedSwitchInvertor.setFont(font)
        self.checkRedSwitchInvertor.setStyleSheet("QCheckBox{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    border-radius: 5;\n"
"    border: none;\n"
"    padding: 2;\n"
"}")
        self.checkRedSwitchInvertor.setText("")
        self.checkRedSwitchInvertor.setObjectName("checkRedSwitchInvertor")
        self.checkGreenSwitchInvertor = QtWidgets.QCheckBox(self.centralwidget)
        self.checkGreenSwitchInvertor.setGeometry(QtCore.QRect(293, 555, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkGreenSwitchInvertor.setFont(font)
        self.checkGreenSwitchInvertor.setStyleSheet("QCheckBox{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    border-radius: 5;\n"
"    border: none;\n"
"    padding: 2;\n"
"}")
        self.checkGreenSwitchInvertor.setText("")
        self.checkGreenSwitchInvertor.setObjectName("checkGreenSwitchInvertor")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setEnabled(True)
        self.label_27.setGeometry(QtCore.QRect(20, 526, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.checkYellowLineInvertor = QtWidgets.QCheckBox(self.centralwidget)
        self.checkYellowLineInvertor.setGeometry(QtCore.QRect(198, 530, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkYellowLineInvertor.setFont(font)
        self.checkYellowLineInvertor.setStyleSheet("QCheckBox{\n"
"    background-color: rgb(252,237,63); \n"
"    border-top-left-radius: 5;\n"
"    border-bottom-left-radius: 5;\n"
"    border: none;\n"
"    padding-left: 3.5;\n"
"}\n"
"")
        self.checkYellowLineInvertor.setText("")
        self.checkYellowLineInvertor.setObjectName("checkYellowLineInvertor")
        self.checkYellowSwitchInvertor = QtWidgets.QCheckBox(self.centralwidget)
        self.checkYellowSwitchInvertor.setGeometry(QtCore.QRect(200, 555, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkYellowSwitchInvertor.setFont(font)
        self.checkYellowSwitchInvertor.setStyleSheet("QCheckBox{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    border-radius: 5;\n"
"    border: none;\n"
"    padding: 2;\n"
"}")
        self.checkYellowSwitchInvertor.setText("")
        self.checkYellowSwitchInvertor.setObjectName("checkYellowSwitchInvertor")
        self.checkYellowSwitchOther = QtWidgets.QCheckBox(self.centralwidget)
        self.checkYellowSwitchOther.setGeometry(QtCore.QRect(400, 555, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkYellowSwitchOther.setFont(font)
        self.checkYellowSwitchOther.setStyleSheet("QCheckBox{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    border-radius: 5;\n"
"    border: none;\n"
"    padding: 2;\n"
"}")
        self.checkYellowSwitchOther.setText("")
        self.checkYellowSwitchOther.setObjectName("checkYellowSwitchOther")
        self.checkYellowLineOther = QtWidgets.QCheckBox(self.centralwidget)
        self.checkYellowLineOther.setGeometry(QtCore.QRect(398, 530, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkYellowLineOther.setFont(font)
        self.checkYellowLineOther.setStyleSheet("QCheckBox{\n"
"    background-color: rgb(252,237,63); \n"
"    border-top-left-radius: 5;\n"
"    border-bottom-left-radius: 5;\n"
"    border: none;\n"
"    padding-left: 3.5;\n"
"}")
        self.checkYellowLineOther.setText("")
        self.checkYellowLineOther.setObjectName("checkYellowLineOther")
        self.inputParam5_out = QtWidgets.QLineEdit(self.centralwidget)
        self.inputParam5_out.setGeometry(QtCore.QRect(751, 370, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.inputParam5_out.setFont(font)
        self.inputParam5_out.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputParam5_out.setInputMask("")
        self.inputParam5_out.setText("")
        self.inputParam5_out.setPlaceholderText("")
        self.inputParam5_out.setObjectName("inputParam5_out")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 424, 931, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setEnabled(True)
        self.label_29.setGeometry(QtCore.QRect(20, 440, 311, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setGeometry(QtCore.QRect(516, 252, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnReset.setFont(font)
        self.btnReset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReset.setStyleSheet("QPushButton{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color:rgba(0, 0, 0, 0.5);\n"
"    border: none;\n"
"    border-radius: 5;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"}\n"
"")
        self.btnReset.setObjectName("btnReset")
        self.spinBox_numInvertor = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numInvertor.setGeometry(QtCore.QRect(154, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_numInvertor.setFont(font)
        self.spinBox_numInvertor.setStyleSheet("QSpinBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px;\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QSpinBox:up-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-top-right-radius: 6;\n"
"    border: none;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"QSpinBox:down-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-bottom-right-radius: 6;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"\n"
"}")
        self.spinBox_numInvertor.setReadOnly(False)
        self.spinBox_numInvertor.setObjectName("spinBox_numInvertor")
        self.spinBox_numOther = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numOther.setGeometry(QtCore.QRect(355, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_numOther.setFont(font)
        self.spinBox_numOther.setStyleSheet("QSpinBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px;\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QSpinBox:up-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-top-right-radius: 6;\n"
"    border: none;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"QSpinBox:down-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-bottom-right-radius: 6;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"\n"
"}")
        self.spinBox_numOther.setReadOnly(False)
        self.spinBox_numOther.setObjectName("spinBox_numOther")
        self.btnSaveConfig = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveConfig.setGeometry(QtCore.QRect(14, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnSaveConfig.setFont(font)
        self.btnSaveConfig.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSaveConfig.setStyleSheet("QPushButton{\n"
"    /*background-color: #196dff;*/\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    border-bottom: 3px solid white;\n"
"    border-radius: 3; \n"
"}\n"
"QPushButton:pressed{\n"
"    border-bottom: 0px solid white;\n"
"    border-radius: 3;\n"
"}")
        self.btnSaveConfig.setText("")
        self.btnSaveConfig.setObjectName("btnSaveConfig")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(198, 530, 31, 48))
        self.label_4.setStyleSheet("QLabel{\n"
"    background-color: rgb(252,237,63); \n"
"    border-top-left-radius: 5;\n"
"    border-bottom-left-radius: 5;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(229, 530, 31, 47))
        self.label_5.setStyleSheet("QLabel{\n"
"    background-color:red; \n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(291, 530, 31, 47))
        self.label_6.setStyleSheet("QLabel{\n"
"    background-color:lightgreen; \n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 530, 31, 47))
        self.label_7.setStyleSheet("QLabel{\n"
"    background-color:blue; \n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(322, 530, 31, 47))
        self.label_8.setStyleSheet("QLabel{\n"
"    background-color:black; \n"
"    border-top-right-radius: 5;\n"
"    border-bottom-right-radius: 5; \n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(460, 530, 31, 47))
        self.label_19.setStyleSheet("QLabel{\n"
"    background-color:blue; \n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(522, 530, 31, 47))
        self.label_20.setStyleSheet("QLabel{\n"
"    background-color:black; \n"
"    border-top-right-radius: 5;\n"
"    border-bottom-right-radius: 5; \n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(429, 530, 31, 47))
        self.label_21.setStyleSheet("QLabel{\n"
"    background-color:red; \n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(491, 530, 31, 47))
        self.label_28.setStyleSheet("QLabel{\n"
"    background-color:lightgreen; \n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(398, 530, 31, 47))
        self.label_30.setStyleSheet("QLabel{\n"
"    background-color: rgb(252,237,63); \n"
"    border-top-left-radius: 5;\n"
"    border-bottom-left-radius: 5;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.btnOpenScheme = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenScheme.setGeometry(QtCore.QRect(562, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnOpenScheme.setFont(font)
        self.btnOpenScheme.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOpenScheme.setStyleSheet("QPushButton{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color:rgba(0, 0, 0, 0.5);\n"
"    border: none;\n"
"    border-radius: 5;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"}\n"
"")
        self.btnOpenScheme.setObjectName("btnOpenScheme")
        self.label_28.raise_()
        self.label_20.raise_()
        self.label_19.raise_()
        self.label_30.raise_()
        self.label_21.raise_()
        self.label_8.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.inputName_other.raise_()
        self.textConsoleDraw.raise_()
        self.btnDraw.raise_()
        self.inputPower_invertor.raise_()
        self.inputAmperage_invertor.raise_()
        self.checkUse_threePhase.raise_()
        self.checkUse_yzip.raise_()
        self.checkUse_counter.raise_()
        self.inputName_invertor.raise_()
        self.inputPower_other.raise_()
        self.inputAmperage_other.raise_()
        self.inputType_other.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.spinBox_countInvertor.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.spinBox_countOther.raise_()
        self.btnOpen_otherParams.raise_()
        self.inputParam1_invertor.raise_()
        self.inputParam2_invertor.raise_()
        self.inputParam2_other.raise_()
        self.inputParam1_other.raise_()
        self.inputParam6_invertor.raise_()
        self.inputParam6_other.raise_()
        self.inputParam7_invertor.raise_()
        self.inputParam7_other.raise_()
        self.label_16.raise_()
        self.inputParam2_yzip.raise_()
        self.inputParam1_yzip.raise_()
        self.inputParam3_yzip.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.inputParam2_out.raise_()
        self.inputParam4_out.raise_()
        self.inputParam3_out.raise_()
        self.label_25.raise_()
        self.checkRedLineInvertor.raise_()
        self.checkBlueLineInvertor.raise_()
        self.checkGreenLineInvertor.raise_()
        self.checkBlackLineInvertor.raise_()
        self.checkBlueLineOther.raise_()
        self.checkRedLineOther.raise_()
        self.checkBlackLineOther.raise_()
        self.checkGreenLineOther.raise_()
        self.label_26.raise_()
        self.checkBlueSwitchOther.raise_()
        self.checkRedSwitchOther.raise_()
        self.checkBlueSwitchInvertor.raise_()
        self.checkGreenSwitchOther.raise_()
        self.checkRedSwitchInvertor.raise_()
        self.checkGreenSwitchInvertor.raise_()
        self.label_27.raise_()
        self.checkYellowLineInvertor.raise_()
        self.checkYellowSwitchInvertor.raise_()
        self.checkYellowSwitchOther.raise_()
        self.checkYellowLineOther.raise_()
        self.inputParam5_out.raise_()
        self.line.raise_()
        self.label_29.raise_()
        self.btnReset.raise_()
        self.spinBox_numInvertor.raise_()
        self.spinBox_numOther.raise_()
        self.btnSaveConfig.raise_()
        self.btnOpenScheme.raise_()
        WindowDrawSchemesTwo.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(WindowDrawSchemesTwo)
        self.statusBar.setObjectName("statusBar")
        WindowDrawSchemesTwo.setStatusBar(self.statusBar)

        self.retranslateUi(WindowDrawSchemesTwo)
        QtCore.QMetaObject.connectSlotsByName(WindowDrawSchemesTwo)

    def retranslateUi(self, WindowDrawSchemesTwo):
        _translate = QtCore.QCoreApplication.translate
        WindowDrawSchemesTwo.setWindowTitle(_translate("WindowDrawSchemesTwo", "Схема подключения"))
        self.textConsoleDraw.setPlaceholderText(_translate("WindowDrawSchemesTwo", "Ход построения"))
        self.btnDraw.setText(_translate("WindowDrawSchemesTwo", "Построить"))
        self.checkUse_threePhase.setText(_translate("WindowDrawSchemesTwo", "Трёхфазная система"))
        self.checkUse_yzip.setText(_translate("WindowDrawSchemesTwo", "УЗИП"))
        self.checkUse_counter.setText(_translate("WindowDrawSchemesTwo", "Счетчик"))
        self.label_9.setText(_translate("WindowDrawSchemesTwo", "Инвертор"))
        self.label_10.setText(_translate("WindowDrawSchemesTwo", "Доп"))
        self.label_11.setText(_translate("WindowDrawSchemesTwo", "Название:"))
        self.label_12.setText(_translate("WindowDrawSchemesTwo", "Число:"))
        self.label_13.setText(_translate("WindowDrawSchemesTwo", "Мощность, кВт:"))
        self.label_14.setText(_translate("WindowDrawSchemesTwo", "Сила тока, А:"))
        self.label_15.setText(_translate("WindowDrawSchemesTwo", "Тип:"))
        self.btnOpen_otherParams.setText(_translate("WindowDrawSchemesTwo", "Подробнее"))
        self.label_16.setText(_translate("WindowDrawSchemesTwo", "УЗИП"))
        self.label_17.setText(_translate("WindowDrawSchemesTwo", "Тип"))
        self.label_18.setText(_translate("WindowDrawSchemesTwo", "Ном. ток, А"))
        self.label_22.setText(_translate("WindowDrawSchemesTwo", "Марка"))
        self.label_23.setText(_translate("WindowDrawSchemesTwo", "Длина"))
        self.label_24.setText(_translate("WindowDrawSchemesTwo", "Дополнительные параметры"))
        self.label_25.setText(_translate("WindowDrawSchemesTwo", "Параметры выхода"))
        self.checkRedLineInvertor.setToolTip(_translate("WindowDrawSchemesTwo", "Красный провод"))
        self.checkBlueLineInvertor.setToolTip(_translate("WindowDrawSchemesTwo", "Синий провод"))
        self.checkGreenLineInvertor.setToolTip(_translate("WindowDrawSchemesTwo", "Зеленый провод"))
        self.checkBlackLineInvertor.setToolTip(_translate("WindowDrawSchemesTwo", "Черный провод"))
        self.checkBlueLineOther.setToolTip(_translate("WindowDrawSchemesTwo", "Синий провод"))
        self.checkRedLineOther.setToolTip(_translate("WindowDrawSchemesTwo", "Красный провод"))
        self.checkBlackLineOther.setToolTip(_translate("WindowDrawSchemesTwo", "Черный провод"))
        self.checkGreenLineOther.setToolTip(_translate("WindowDrawSchemesTwo", "Зеленый провод"))
        self.label_26.setText(_translate("WindowDrawSchemesTwo", "Switch"))
        self.label_27.setText(_translate("WindowDrawSchemesTwo", "Провода"))
        self.checkYellowLineInvertor.setToolTip(_translate("WindowDrawSchemesTwo", "Желтый провод"))
        self.checkYellowLineOther.setToolTip(_translate("WindowDrawSchemesTwo", "Желтый провод"))
        self.label_29.setText(_translate("WindowDrawSchemesTwo", "Кабельная линия"))
        self.btnReset.setToolTip(_translate("WindowDrawSchemesTwo", "Добавить MPPT"))
        self.btnReset.setText(_translate("WindowDrawSchemesTwo", "⭯"))
        self.btnOpenScheme.setText(_translate("WindowDrawSchemesTwo", "Открыть"))
