# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designDrawStructuralScheme.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowDrawSchemes(object):
    def setupUi(self, WindowDrawSchemes):
        WindowDrawSchemes.setObjectName("WindowDrawSchemes")
        WindowDrawSchemes.setEnabled(True)
        WindowDrawSchemes.resize(382, 510)
        font = QtGui.QFont()
        font.setFamily("Arial")
        WindowDrawSchemes.setFont(font)
        WindowDrawSchemes.setFocusPolicy(QtCore.Qt.NoFocus)
        WindowDrawSchemes.setStyleSheet("QMainWindow {\n"
"    background-color: white\n"
"}\n"
"QScrollBar:vertical {              \n"
"    background: #e5e5ea;\n"
"    border-radius: 3;\n"
"    border: none;\n"
"    max-width: 8px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #196dff;\n"
"    border-radius: 3;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #3b83ff; \n"
"    min-height: 0px;\n"
"    border-radius: 3;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: #e5e5ea;\n"
"    border: none;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background: transparent;\n"
"    border-radius: 6;\n"
"    border: none;\n"
"    outline:0px;\n"
"    selection-background-color: white;\n"
"    selection-color: #196dff;\n"
"    padding: 8 0 8 0;\n"
"}")
        WindowDrawSchemes.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(WindowDrawSchemes)
        self.centralwidget.setStyleSheet("background-color: #fff;")
        self.centralwidget.setObjectName("centralwidget")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(20, 12, 351, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.label_8.setObjectName("label_8")
        self.inputCountPV = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCountPV.setEnabled(True)
        self.inputCountPV.setGeometry(QtCore.QRect(20, 101, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.inputCountPV.setFont(font)
        self.inputCountPV.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.inputCountPV.setInputMask("")
        self.inputCountPV.setText("")
        self.inputCountPV.setReadOnly(True)
        self.inputCountPV.setPlaceholderText("")
        self.inputCountPV.setObjectName("inputCountPV")
        self.btnDraw = QtWidgets.QPushButton(self.centralwidget)
        self.btnDraw.setGeometry(QtCore.QRect(20, 384, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnDraw.setFont(font)
        self.btnDraw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDraw.setStyleSheet("QPushButton{\n"
"    background-color: rgb(60,178,0);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(60,178,0, 0.85); \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(255, 255, 255, 0.7);\n"
"    border-radius: 12;\n"
"}")
        self.btnDraw.setObjectName("btnDraw")
        self.checkWifi = QtWidgets.QCheckBox(self.centralwidget)
        self.checkWifi.setGeometry(QtCore.QRect(20, 296, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkWifi.setFont(font)
        self.checkWifi.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.checkWifi.setObjectName("checkWifi")
        self.spinBox_numInvertor = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numInvertor.setGeometry(QtCore.QRect(20, 53, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_numInvertor.setFont(font)
        self.spinBox_numInvertor.setStyleSheet("QSpinBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QSpinBox:up-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-top-right-radius: 6;\n"
"    border: none;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"QSpinBox:down-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-bottom-right-radius: 6;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"\n"
"}")
        self.spinBox_numInvertor.setObjectName("spinBox_numInvertor")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setEnabled(True)
        self.label_11.setGeometry(QtCore.QRect(85, 102, 111, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.label_11.setObjectName("label_11")
        self.btnSaveConfig = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveConfig.setGeometry(QtCore.QRect(310, 382, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnSaveConfig.setFont(font)
        self.btnSaveConfig.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSaveConfig.setStyleSheet("QPushButton{\n"
"    /*background-color: #196dff;*/\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    border-bottom: 3px solid white;\n"
"    border-radius: 3; \n"
"}\n"
"QPushButton:pressed{\n"
"    border-bottom: 0px solid white;\n"
"    border-radius: 3;\n"
"}")
        self.btnSaveConfig.setText("")
        self.btnSaveConfig.setObjectName("btnSaveConfig")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setEnabled(True)
        self.label_20.setGeometry(QtCore.QRect(85, 51, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.label_20.setObjectName("label_20")
        self.checkUnitedInternet = QtWidgets.QCheckBox(self.centralwidget)
        self.checkUnitedInternet.setGeometry(QtCore.QRect(200, 311, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkUnitedInternet.setFont(font)
        self.checkUnitedInternet.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.checkUnitedInternet.setObjectName("checkUnitedInternet")
        self.checkUnitedOut = QtWidgets.QCheckBox(self.centralwidget)
        self.checkUnitedOut.setGeometry(QtCore.QRect(200, 287, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkUnitedOut.setFont(font)
        self.checkUnitedOut.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.checkUnitedOut.setObjectName("checkUnitedOut")
        self.checkYzipLeft = QtWidgets.QCheckBox(self.centralwidget)
        self.checkYzipLeft.setGeometry(QtCore.QRect(20, 236, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkYzipLeft.setFont(font)
        self.checkYzipLeft.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.checkYzipLeft.setObjectName("checkYzipLeft")
        self.checkController = QtWidgets.QCheckBox(self.centralwidget)
        self.checkController.setGeometry(QtCore.QRect(20, 155, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkController.setFont(font)
        self.checkController.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.checkController.setObjectName("checkController")
        self.checkCommutator = QtWidgets.QCheckBox(self.centralwidget)
        self.checkCommutator.setGeometry(QtCore.QRect(200, 155, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkCommutator.setFont(font)
        self.checkCommutator.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.checkCommutator.setObjectName("checkCommutator")
        self.inputName_invertor = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName_invertor.setEnabled(True)
        self.inputName_invertor.setGeometry(QtCore.QRect(150, 51, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.inputName_invertor.setFont(font)
        self.inputName_invertor.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,0); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.inputName_invertor.setInputMask("")
        self.inputName_invertor.setText("")
        self.inputName_invertor.setFrame(True)
        self.inputName_invertor.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.inputName_invertor.setReadOnly(True)
        self.inputName_invertor.setPlaceholderText("")
        self.inputName_invertor.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.inputName_invertor.setObjectName("inputName_invertor")
        self.checkYzipRight = QtWidgets.QCheckBox(self.centralwidget)
        self.checkYzipRight.setGeometry(QtCore.QRect(200, 236, 101, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkYzipRight.setFont(font)
        self.checkYzipRight.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.checkYzipRight.setObjectName("checkYzipRight")
        self.spinBox_CountInvertors = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_CountInvertors.setGeometry(QtCore.QRect(200, 100, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_CountInvertors.setFont(font)
        self.spinBox_CountInvertors.setStyleSheet("QSpinBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QSpinBox:up-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-top-right-radius: 6;\n"
"    border: none;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"QSpinBox:down-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-bottom-right-radius: 6;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"\n"
"}")
        self.spinBox_CountInvertors.setObjectName("spinBox_CountInvertors")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setEnabled(True)
        self.label_21.setGeometry(QtCore.QRect(252, 100, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setEnabled(True)
        self.label_14.setGeometry(QtCore.QRect(20, 267, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.btnOpenScheme = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenScheme.setGeometry(QtCore.QRect(116, 423, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnOpenScheme.setFont(font)
        self.btnOpenScheme.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOpenScheme.setStyleSheet("QPushButton{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color:rgba(0, 0, 0, 0.5);\n"
"    border: none;\n"
"    border-radius: 5;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"}\n"
"")
        self.btnOpenScheme.setObjectName("btnOpenScheme")
        self.inputTitleOtherDevice = QtWidgets.QLineEdit(self.centralwidget)
        self.inputTitleOtherDevice.setEnabled(True)
        self.inputTitleOtherDevice.setGeometry(QtCore.QRect(20, 186, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.inputTitleOtherDevice.setFont(font)
        self.inputTitleOtherDevice.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"")
        self.inputTitleOtherDevice.setInputMask("")
        self.inputTitleOtherDevice.setText("")
        self.inputTitleOtherDevice.setReadOnly(False)
        self.inputTitleOtherDevice.setPlaceholderText("")
        self.inputTitleOtherDevice.setObjectName("inputTitleOtherDevice")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setEnabled(True)
        self.label_22.setGeometry(QtCore.QRect(201, 187, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.label_22.setObjectName("label_22")
        self.checkWebServer = QtWidgets.QCheckBox(self.centralwidget)
        self.checkWebServer.setGeometry(QtCore.QRect(20, 330, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkWebServer.setFont(font)
        self.checkWebServer.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.checkWebServer.setObjectName("checkWebServer")
        self.checkYzipRight.raise_()
        self.label_20.raise_()
        self.label_8.raise_()
        self.inputCountPV.raise_()
        self.btnDraw.raise_()
        self.checkWifi.raise_()
        self.spinBox_numInvertor.raise_()
        self.label_11.raise_()
        self.btnSaveConfig.raise_()
        self.checkUnitedInternet.raise_()
        self.checkUnitedOut.raise_()
        self.checkYzipLeft.raise_()
        self.checkController.raise_()
        self.checkCommutator.raise_()
        self.inputName_invertor.raise_()
        self.spinBox_CountInvertors.raise_()
        self.label_21.raise_()
        self.label_14.raise_()
        self.btnOpenScheme.raise_()
        self.inputTitleOtherDevice.raise_()
        self.label_22.raise_()
        self.checkWebServer.raise_()
        WindowDrawSchemes.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(WindowDrawSchemes)
        self.statusBar.setObjectName("statusBar")
        WindowDrawSchemes.setStatusBar(self.statusBar)

        self.retranslateUi(WindowDrawSchemes)
        QtCore.QMetaObject.connectSlotsByName(WindowDrawSchemes)

    def retranslateUi(self, WindowDrawSchemes):
        _translate = QtCore.QCoreApplication.translate
        WindowDrawSchemes.setWindowTitle(_translate("WindowDrawSchemes", "Структурная схема"))
        self.label_8.setText(_translate("WindowDrawSchemes", "Конфигурация структурной схемы"))
        self.inputCountPV.setToolTip(_translate("WindowDrawSchemes", "Количество MPPT в инверторе"))
        self.btnDraw.setText(_translate("WindowDrawSchemes", "Построить"))
        self.checkWifi.setToolTip(_translate("WindowDrawSchemes", "Применяет Y конекторы, если это допустимо "))
        self.checkWifi.setText(_translate("WindowDrawSchemes", "Wi-Fi"))
        self.spinBox_numInvertor.setToolTip(_translate("WindowDrawSchemes", "Количество схем одинаковых инверторов"))
        self.label_11.setText(_translate("WindowDrawSchemes", "Кол-во\n"
"цепочек"))
        self.label_20.setText(_translate("WindowDrawSchemes", "Инвертор"))
        self.checkUnitedInternet.setToolTip(_translate("WindowDrawSchemes", "Применяет Y конекторы, если это допустимо "))
        self.checkUnitedInternet.setText(_translate("WindowDrawSchemes", "\n"
"Объединенный \n"
"интернет кабель"))
        self.checkUnitedOut.setToolTip(_translate("WindowDrawSchemes", "Применяет Y конекторы, если это допустимо "))
        self.checkUnitedOut.setText(_translate("WindowDrawSchemes", "Объединенный выход"))
        self.checkYzipLeft.setToolTip(_translate("WindowDrawSchemes", "Применяет Y конекторы, если это допустимо "))
        self.checkYzipLeft.setText(_translate("WindowDrawSchemes", "Левый"))
        self.checkController.setToolTip(_translate("WindowDrawSchemes", "Применяет Y конекторы, если это допустимо "))
        self.checkController.setText(_translate("WindowDrawSchemes", "Контроллер"))
        self.checkCommutator.setToolTip(_translate("WindowDrawSchemes", "Применяет Y конекторы, если это допустимо "))
        self.checkCommutator.setText(_translate("WindowDrawSchemes", "Коммутатор"))
        self.inputName_invertor.setToolTip(_translate("WindowDrawSchemes", "Количество MPPT в инверторе"))
        self.checkYzipRight.setToolTip(_translate("WindowDrawSchemes", "Применяет Y конекторы, если это допустимо "))
        self.checkYzipRight.setText(_translate("WindowDrawSchemes", "Правый"))
        self.spinBox_CountInvertors.setToolTip(_translate("WindowDrawSchemes", "Количество схем одинаковых инверторов"))
        self.label_21.setText(_translate("WindowDrawSchemes", "Кол-во\n"
"инверторов"))
        self.label_14.setText(_translate("WindowDrawSchemes", "Общие параметры"))
        self.btnOpenScheme.setText(_translate("WindowDrawSchemes", "Открыть"))
        self.inputTitleOtherDevice.setToolTip(_translate("WindowDrawSchemes", "Количество MPPT в инверторе"))
        self.label_22.setText(_translate("WindowDrawSchemes", "Название модуля"))
        self.checkWebServer.setToolTip(_translate("WindowDrawSchemes", "Применяет Y конекторы, если это допустимо "))
        self.checkWebServer.setText(_translate("WindowDrawSchemes", "Web сервер"))
