# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designRepPDF.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1423, 408)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: white\n"
"}\n"
"QScrollBar:vertical {              \n"
"    background: #e5e5ea;\n"
"    border-radius: 3;\n"
"    border: none;\n"
"    max-width: 8px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #196dff;\n"
"    border-radius: 3;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #3b83ff; \n"
"    min-height: 0px;\n"
"    border-radius: 3;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: #e5e5ea;\n"
"    border: none;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background: transparent;\n"
"    border-radius: 6;\n"
"    border: none;\n"
"    outline:0px;\n"
"    selection-background-color: white;\n"
"    selection-color: #196dff;\n"
"    padding: 8 0 8 0;\n"
"}")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #fff;")
        self.centralwidget.setObjectName("centralwidget")
        self.textConsole = QtWidgets.QTextBrowser(self.centralwidget)
        self.textConsole.setEnabled(True)
        self.textConsole.setGeometry(QtCore.QRect(20, 153, 181, 204))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.textConsole.setFont(font)
        self.textConsole.setStyleSheet("QTextBrowser{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding: 8 4 52 8;\n"
"}\n"
"")
        self.textConsole.setObjectName("textConsole")
        self.btnTwo = QtWidgets.QPushButton(self.centralwidget)
        self.btnTwo.setGeometry(QtCore.QRect(112, 90, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.btnTwo.setFont(font)
        self.btnTwo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTwo.setStyleSheet("QPushButton{\n"
"    background-color: rgba(229,229,234,1);\n"
"    color: #196dff;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #dceaff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(25, 109, 255, 0.7); \n"
"    border-radius: 12;\n"
"}")
        self.btnTwo.setObjectName("btnTwo")
        self.btnOne = QtWidgets.QPushButton(self.centralwidget)
        self.btnOne.setGeometry(QtCore.QRect(14, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.btnOne.setFont(font)
        self.btnOne.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOne.setStyleSheet("QPushButton{\n"
"    background-color: #196dff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #3b83ff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(255, 255, 255, 0.7);\n"
"    border-radius: 12;\n"
"}")
        self.btnOne.setObjectName("btnOne")
        self.btnFour = QtWidgets.QPushButton(self.centralwidget)
        self.btnFour.setGeometry(QtCore.QRect(332, 90, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.btnFour.setFont(font)
        self.btnFour.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFour.setStyleSheet("QPushButton{\n"
"    background-color: rgba(229,229,234,1);\n"
"    color: #196dff;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #dceaff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(25, 109, 255, 0.7); \n"
"    border-radius: 12;\n"
"}")
        self.btnFour.setObjectName("btnFour")
        self.btnThree = QtWidgets.QPushButton(self.centralwidget)
        self.btnThree.setGeometry(QtCore.QRect(222, 90, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.btnThree.setFont(font)
        self.btnThree.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnThree.setStyleSheet("QPushButton{\n"
"    background-color: rgba(229,229,234,1);\n"
"    color: #196dff;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #dceaff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(25, 109, 255, 0.7); \n"
"    border-radius: 12;\n"
"}")
        self.btnThree.setObjectName("btnThree")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 761, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_for_slide = QtWidgets.QLabel(self.centralwidget)
        self.label_for_slide.setGeometry(QtCore.QRect(260, 351, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.label_for_slide.setFont(font)
        self.label_for_slide.setObjectName("label_for_slide")
        self.btnForm = QtWidgets.QPushButton(self.centralwidget)
        self.btnForm.setGeometry(QtCore.QRect(20, 340, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.btnForm.setFont(font)
        self.btnForm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnForm.setStyleSheet("QPushButton{\n"
"    background-color: rgb(60,178,0);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(60,178,0, 0.85); \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(255, 255, 255, 0.7);\n"
"    border-radius: 12;\n"
"}")
        self.btnForm.setObjectName("btnForm")
        self.btnRP5 = QtWidgets.QPushButton(self.centralwidget)
        self.btnRP5.setGeometry(QtCore.QRect(430, 40, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.btnRP5.setFont(font)
        self.btnRP5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRP5.setStyleSheet("QPushButton{\n"
"    background-color: #196dff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #3b83ff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(255, 255, 255, 0.7);\n"
"    border-radius: 12;\n"
"}")
        self.btnRP5.setObjectName("btnRP5")
        self.btnDrawScheme = QtWidgets.QPushButton(self.centralwidget)
        self.btnDrawScheme.setGeometry(QtCore.QRect(550, 90, 114, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.btnDrawScheme.setFont(font)
        self.btnDrawScheme.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDrawScheme.setStyleSheet("QPushButton{\n"
"    background-color: rgba(229,229,234,1);\n"
"    color: #196dff;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #dceaff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(25, 109, 255, 0.7); \n"
"    border-radius: 12;\n"
"}")
        self.btnDrawScheme.setObjectName("btnDrawScheme")
        self.btnDrawSchemeTwo = QtWidgets.QPushButton(self.centralwidget)
        self.btnDrawSchemeTwo.setGeometry(QtCore.QRect(673, 90, 115, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.btnDrawSchemeTwo.setFont(font)
        self.btnDrawSchemeTwo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDrawSchemeTwo.setStyleSheet("QPushButton{\n"
"    background-color: rgba(229,229,234,1);\n"
"    color: #196dff;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #dceaff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(25, 109, 255, 0.7); \n"
"    border-radius: 12;\n"
"}")
        self.btnDrawSchemeTwo.setObjectName("btnDrawSchemeTwo")
        self.inputTitleProject = QtWidgets.QLineEdit(self.centralwidget)
        self.inputTitleProject.setGeometry(QtCore.QRect(358, 153, 428, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.inputTitleProject.setFont(font)
        self.inputTitleProject.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputTitleProject.setInputMask("")
        self.inputTitleProject.setText("")
        self.inputTitleProject.setPlaceholderText("")
        self.inputTitleProject.setObjectName("inputTitleProject")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(211, 160, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(211, 237, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.inputClient = QtWidgets.QLineEdit(self.centralwidget)
        self.inputClient.setGeometry(QtCore.QRect(358, 230, 429, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.inputClient.setFont(font)
        self.inputClient.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputClient.setInputMask("")
        self.inputClient.setText("")
        self.inputClient.setPlaceholderText("")
        self.inputClient.setObjectName("inputClient")
        self.listRoof = QtWidgets.QComboBox(self.centralwidget)
        self.listRoof.setGeometry(QtCore.QRect(358, 270, 429, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.listRoof.setFont(font)
        self.listRoof.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listRoof.setAutoFillBackground(False)
        self.listRoof.setStyleSheet("QComboBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border: none;\n"
"    border-radius: 6;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"")
        self.listRoof.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listRoof.setEditable(False)
        self.listRoof.setCurrentText("")
        self.listRoof.setPlaceholderText("")
        self.listRoof.setModelColumn(0)
        self.listRoof.setObjectName("listRoof")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(211, 277, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btnSchemes = QtWidgets.QPushButton(self.centralwidget)
        self.btnSchemes.setGeometry(QtCore.QRect(548, 40, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.btnSchemes.setFont(font)
        self.btnSchemes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSchemes.setStyleSheet("QPushButton{\n"
"    background-color: #196dff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #3b83ff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(255, 255, 255, 0.7);\n"
"    border-radius: 12;\n"
"}")
        self.btnSchemes.setObjectName("btnSchemes")
        self.btnDevice = QtWidgets.QPushButton(self.centralwidget)
        self.btnDevice.setGeometry(QtCore.QRect(142, 40, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setKerning(True)
        self.btnDevice.setFont(font)
        self.btnDevice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDevice.setStyleSheet("QPushButton{\n"
"    background-color: #196dff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #3b83ff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(255, 255, 255, 0.7);\n"
"    border-radius: 12;\n"
"}")
        self.btnDevice.setObjectName("btnDevice")
        self.checkBox_8_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8_1.setGeometry(QtCore.QRect(739, 197, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_8_1.setFont(font)
        self.checkBox_8_1.setAutoFillBackground(False)
        self.checkBox_8_1.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_8_1.setObjectName("checkBox_8_1")
        self.checkBox_8_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8_2.setGeometry(QtCore.QRect(739, 216, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_8_2.setFont(font)
        self.checkBox_8_2.setAutoFillBackground(False)
        self.checkBox_8_2.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_8_2.setObjectName("checkBox_8_2")
        self.checkBox_8_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8_4.setGeometry(QtCore.QRect(739, 254, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_8_4.setFont(font)
        self.checkBox_8_4.setAutoFillBackground(False)
        self.checkBox_8_4.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_8_4.setObjectName("checkBox_8_4")
        self.checkBox_8_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8_3.setGeometry(QtCore.QRect(739, 235, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_8_3.setFont(font)
        self.checkBox_8_3.setAutoFillBackground(False)
        self.checkBox_8_3.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_8_3.setObjectName("checkBox_8_3")
        self.checkBox_5_1_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5_1_3.setGeometry(QtCore.QRect(631, 243, 61, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_5_1_3.setFont(font)
        self.checkBox_5_1_3.setAutoFillBackground(False)
        self.checkBox_5_1_3.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_5_1_3.setObjectName("checkBox_5_1_3")
        self.checkBox_3_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3_1.setGeometry(QtCore.QRect(465, 196, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_3_1.setFont(font)
        self.checkBox_3_1.setAutoFillBackground(False)
        self.checkBox_3_1.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_3_1.setObjectName("checkBox_3_1")
        self.checkBox_8_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8_5.setGeometry(QtCore.QRect(739, 273, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_8_5.setFont(font)
        self.checkBox_8_5.setAutoFillBackground(False)
        self.checkBox_8_5.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_8_5.setObjectName("checkBox_8_5")
        self.checkBox_8_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8_6.setGeometry(QtCore.QRect(739, 292, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_8_6.setFont(font)
        self.checkBox_8_6.setAutoFillBackground(False)
        self.checkBox_8_6.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_8_6.setObjectName("checkBox_8_6")
        self.checkBox_5_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5_3.setGeometry(QtCore.QRect(575, 236, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_5_3.setFont(font)
        self.checkBox_5_3.setAutoFillBackground(False)
        self.checkBox_5_3.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_5_3.setObjectName("checkBox_5_3")
        self.checkBox_5_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5_4.setGeometry(QtCore.QRect(575, 256, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_5_4.setFont(font)
        self.checkBox_5_4.setAutoFillBackground(False)
        self.checkBox_5_4.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_5_4.setObjectName("checkBox_5_4")
        self.checkBox_5_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5_5.setGeometry(QtCore.QRect(575, 276, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_5_5.setFont(font)
        self.checkBox_5_5.setAutoFillBackground(False)
        self.checkBox_5_5.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_5_5.setObjectName("checkBox_5_5")
        self.checkBox_3_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3_3.setGeometry(QtCore.QRect(465, 236, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_3_3.setFont(font)
        self.checkBox_3_3.setAutoFillBackground(False)
        self.checkBox_3_3.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_3_3.setObjectName("checkBox_3_3")
        self.checkBox_5_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5_6.setGeometry(QtCore.QRect(575, 296, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_5_6.setFont(font)
        self.checkBox_5_6.setAutoFillBackground(False)
        self.checkBox_5_6.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_5_6.setObjectName("checkBox_5_6")
        self.checkBox_5_1_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5_1_2.setGeometry(QtCore.QRect(631, 224, 61, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_5_1_2.setFont(font)
        self.checkBox_5_1_2.setAutoFillBackground(False)
        self.checkBox_5_1_2.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_5_1_2.setObjectName("checkBox_5_1_2")
        self.checkBox_5_1_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5_1_4.setGeometry(QtCore.QRect(631, 262, 61, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_5_1_4.setFont(font)
        self.checkBox_5_1_4.setAutoFillBackground(False)
        self.checkBox_5_1_4.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_5_1_4.setObjectName("checkBox_5_1_4")
        self.checkBox_5_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5_2.setGeometry(QtCore.QRect(575, 216, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_5_2.setFont(font)
        self.checkBox_5_2.setAutoFillBackground(False)
        self.checkBox_5_2.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_5_2.setObjectName("checkBox_5_2")
        self.checkBox_3_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3_4.setGeometry(QtCore.QRect(465, 257, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_3_4.setFont(font)
        self.checkBox_3_4.setAutoFillBackground(False)
        self.checkBox_3_4.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_3_4.setObjectName("checkBox_3_4")
        self.checkBox_3_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3_2.setGeometry(QtCore.QRect(465, 216, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_3_2.setFont(font)
        self.checkBox_3_2.setAutoFillBackground(False)
        self.checkBox_3_2.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_3_2.setObjectName("checkBox_3_2")
        self.checkBox_5_1_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5_1_1.setGeometry(QtCore.QRect(631, 205, 61, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_5_1_1.setFont(font)
        self.checkBox_5_1_1.setAutoFillBackground(False)
        self.checkBox_5_1_1.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_5_1_1.setObjectName("checkBox_5_1_1")
        self.checkBox_5_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5_1.setGeometry(QtCore.QRect(575, 196, 51, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_5_1.setFont(font)
        self.checkBox_5_1.setAutoFillBackground(False)
        self.checkBox_5_1.setStyleSheet("background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;")
        self.checkBox_5_1.setObjectName("checkBox_5_1")
        self.btnLoadScheme2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadScheme2.setGeometry(QtCore.QRect(717, 120, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.btnLoadScheme2.setFont(font)
        self.btnLoadScheme2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLoadScheme2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(229,229,234,1);\n"
"    color: #196dff;\n"
"    border: none;\n"
"    border-radius: 6;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #dceaff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(25, 109, 255, 0.7); \n"
"    border-radius: 6;\n"
"}")
        self.btnLoadScheme2.setObjectName("btnLoadScheme2")
        self.btnLoadScheme1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadScheme1.setGeometry(QtCore.QRect(592, 120, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.btnLoadScheme1.setFont(font)
        self.btnLoadScheme1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLoadScheme1.setStyleSheet("QPushButton{\n"
"    background-color: rgba(229,229,234,1);\n"
"    color: #196dff;\n"
"    border: none;\n"
"    border-radius: 6;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #dceaff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(25, 109, 255, 0.7); \n"
"    border-radius: 6;\n"
"}")
        self.btnLoadScheme1.setObjectName("btnLoadScheme1")
        self.listInvertor_folder = QtWidgets.QComboBox(self.centralwidget)
        self.listInvertor_folder.setGeometry(QtCore.QRect(358, 153, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.listInvertor_folder.setFont(font)
        self.listInvertor_folder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listInvertor_folder.setStyleSheet("QComboBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border: none;\n"
"    border-radius: 6;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"")
        self.listInvertor_folder.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listInvertor_folder.setEditable(False)
        self.listInvertor_folder.setCurrentText("")
        self.listInvertor_folder.setPlaceholderText("")
        self.listInvertor_folder.setObjectName("listInvertor_folder")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(211, 316, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.listInvertor_file = QtWidgets.QComboBox(self.centralwidget)
        self.listInvertor_file.setGeometry(QtCore.QRect(458, 153, 329, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.listInvertor_file.setFont(font)
        self.listInvertor_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listInvertor_file.setStyleSheet("QComboBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border: none;\n"
"    border-radius: 6;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"")
        self.listInvertor_file.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listInvertor_file.setEditable(False)
        self.listInvertor_file.setCurrentText("")
        self.listInvertor_file.setPlaceholderText("")
        self.listInvertor_file.setObjectName("listInvertor_file")
        self.inputCodeProject = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCodeProject.setGeometry(QtCore.QRect(447, 310, 339, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.inputCodeProject.setFont(font)
        self.inputCodeProject.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputCodeProject.setInputMask("")
        self.inputCodeProject.setText("")
        self.inputCodeProject.setPlaceholderText("")
        self.inputCodeProject.setObjectName("inputCodeProject")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(211, 198, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnSlideMenu = QtWidgets.QPushButton(self.centralwidget)
        self.btnSlideMenu.setGeometry(QtCore.QRect(212, 346, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        self.btnSlideMenu.setFont(font)
        self.btnSlideMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSlideMenu.setStyleSheet("QPushButton{\n"
"    background-color: rgba(229,229,234,1);\n"
"    color: #196dff;\n"
"    border: none;\n"
"    border-radius: 6;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #dceaff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(25, 109, 255, 0.7); \n"
"    border-radius: 6;\n"
"}")
        self.btnSlideMenu.setObjectName("btnSlideMenu")
        self.btnShow3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnShow3.setGeometry(QtCore.QRect(459, 177, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnShow3.setFont(font)
        self.btnShow3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnShow3.setStyleSheet("QPushButton{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color:rgba(0, 0, 0, 0.5);\n"
"    border: none;\n"
"    border-radius: 5;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"}\n"
"")
        self.btnShow3.setObjectName("btnShow3")
        self.btnShow5 = QtWidgets.QPushButton(self.centralwidget)
        self.btnShow5.setGeometry(QtCore.QRect(559, 177, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        self.btnShow5.setFont(font)
        self.btnShow5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnShow5.setStyleSheet("QPushButton{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color:rgba(0, 0, 0, 0.5);\n"
"    border: none;\n"
"    border-radius: 5;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"}")
        self.btnShow5.setObjectName("btnShow5")
        self.btnShow8 = QtWidgets.QPushButton(self.centralwidget)
        self.btnShow8.setGeometry(QtCore.QRect(719, 177, 57, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        self.btnShow8.setFont(font)
        self.btnShow8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnShow8.setStyleSheet("QPushButton{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color:rgba(0, 0, 0, 0.5);\n"
"    border: none;\n"
"    border-radius: 5;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"}")
        self.btnShow8.setObjectName("btnShow8")
        self.label_slide_title = QtWidgets.QLabel(self.centralwidget)
        self.label_slide_title.setGeometry(QtCore.QRect(211, 160, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_slide_title.setFont(font)
        self.label_slide_title.setObjectName("label_slide_title")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(685, 158, 34, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(740, 158, 34, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(413, 158, 34, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(522, 158, 34, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(576, 158, 38, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(631, 158, 34, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(467, 158, 34, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_1.setGeometry(QtCore.QRect(358, 158, 34, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_1.setFont(font)
        self.checkBox_1.setObjectName("checkBox_1")
        self.btnOpenPDF = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenPDF.setGeometry(QtCore.QRect(30, 305, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnOpenPDF.setFont(font)
        self.btnOpenPDF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOpenPDF.setStyleSheet("QPushButton{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color:rgba(0, 0, 0, 0.5);\n"
"    border: none;\n"
"    border-radius: 5;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"}\n"
"")
        self.btnOpenPDF.setObjectName("btnOpenPDF")
        self.listPV_file = QtWidgets.QComboBox(self.centralwidget)
        self.listPV_file.setGeometry(QtCore.QRect(458, 191, 329, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.listPV_file.setFont(font)
        self.listPV_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listPV_file.setStyleSheet("QComboBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border: none;\n"
"    border-radius: 6;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"")
        self.listPV_file.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listPV_file.setEditable(False)
        self.listPV_file.setCurrentText("")
        self.listPV_file.setPlaceholderText("")
        self.listPV_file.setObjectName("listPV_file")
        self.listPV_folder = QtWidgets.QComboBox(self.centralwidget)
        self.listPV_folder.setGeometry(QtCore.QRect(358, 191, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.listPV_folder.setFont(font)
        self.listPV_folder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listPV_folder.setStyleSheet("QComboBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border: none;\n"
"    border-radius: 6;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"")
        self.listPV_folder.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listPV_folder.setEditable(False)
        self.listPV_folder.setCurrentText("")
        self.listPV_folder.setPlaceholderText("")
        self.listPV_folder.setObjectName("listPV_folder")
        self.listKTP_folder = QtWidgets.QComboBox(self.centralwidget)
        self.listKTP_folder.setGeometry(QtCore.QRect(358, 230, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.listKTP_folder.setFont(font)
        self.listKTP_folder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listKTP_folder.setStyleSheet("QComboBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border: none;\n"
"    border-radius: 6;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"")
        self.listKTP_folder.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listKTP_folder.setEditable(False)
        self.listKTP_folder.setCurrentText("")
        self.listKTP_folder.setPlaceholderText("")
        self.listKTP_folder.setObjectName("listKTP_folder")
        self.listKTP_file = QtWidgets.QComboBox(self.centralwidget)
        self.listKTP_file.setGeometry(QtCore.QRect(458, 230, 329, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        self.listKTP_file.setFont(font)
        self.listKTP_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listKTP_file.setStyleSheet("QComboBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border: none;\n"
"    border-radius: 6;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"")
        self.listKTP_file.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listKTP_file.setEditable(False)
        self.listKTP_file.setCurrentText("")
        self.listKTP_file.setPlaceholderText("")
        self.listKTP_file.setObjectName("listKTP_file")
        self.inputUDotIn = QtWidgets.QLineEdit(self.centralwidget)
        self.inputUDotIn.setGeometry(QtCore.QRect(359, 310, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.inputUDotIn.setFont(font)
        self.inputUDotIn.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputUDotIn.setInputMask("")
        self.inputUDotIn.setText("")
        self.inputUDotIn.setPlaceholderText("")
        self.inputUDotIn.setObjectName("inputUDotIn")
        self.inputAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAddress.setGeometry(QtCore.QRect(358, 270, 249, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.inputAddress.setFont(font)
        self.inputAddress.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputAddress.setInputMask("")
        self.inputAddress.setText("")
        self.inputAddress.setPlaceholderText("")
        self.inputAddress.setObjectName("inputAddress")
        self.inputObjectType = QtWidgets.QLineEdit(self.centralwidget)
        self.inputObjectType.setGeometry(QtCore.QRect(358, 191, 429, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.inputObjectType.setFont(font)
        self.inputObjectType.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputObjectType.setInputMask("")
        self.inputObjectType.setText("")
        self.inputObjectType.setPlaceholderText("")
        self.inputObjectType.setObjectName("inputObjectType")
        self.inputAddressLat = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAddressLat.setGeometry(QtCore.QRect(616, 270, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.inputAddressLat.setFont(font)
        self.inputAddressLat.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputAddressLat.setInputMask("")
        self.inputAddressLat.setText("")
        self.inputAddressLat.setPlaceholderText("")
        self.inputAddressLat.setObjectName("inputAddressLat")
        self.inputAddressLong = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAddressLong.setGeometry(QtCore.QRect(706, 270, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.inputAddressLong.setFont(font)
        self.inputAddressLong.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.inputAddressLong.setInputMask("")
        self.inputAddressLong.setText("")
        self.inputAddressLong.setPlaceholderText("")
        self.inputAddressLong.setObjectName("inputAddressLong")
        self.btnAddInvertor = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddInvertor.setGeometry(QtCore.QRect(781, 153, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.btnAddInvertor.setFont(font)
        self.btnAddInvertor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddInvertor.setStyleSheet("QPushButton{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color:rgba(0, 0, 0, 0.5);\n"
"    border: none;\n"
"    border-radius: 5;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"}\n"
"")
        self.btnAddInvertor.setObjectName("btnAddInvertor")
        self.spinBox_numInvertor = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numInvertor.setGeometry(QtCore.QRect(746, 153, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.spinBox_numInvertor.setFont(font)
        self.spinBox_numInvertor.setStyleSheet("QSpinBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QSpinBox:up-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-top-right-radius: 6;\n"
"    border: none;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"QSpinBox:down-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-bottom-right-radius: 6;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"\n"
"}")
        self.spinBox_numInvertor.setObjectName("spinBox_numInvertor")
        self.btnAddPV = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddPV.setGeometry(QtCore.QRect(781, 190, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.btnAddPV.setFont(font)
        self.btnAddPV.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddPV.setStyleSheet("QPushButton{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color:rgba(0, 0, 0, 0.5);\n"
"    border: none;\n"
"    border-radius: 5;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"}\n"
"")
        self.btnAddPV.setObjectName("btnAddPV")
        self.spinBox_numPV = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numPV.setGeometry(QtCore.QRect(746, 190, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.spinBox_numPV.setFont(font)
        self.spinBox_numPV.setStyleSheet("QSpinBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QSpinBox:up-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-top-right-radius: 6;\n"
"    border: none;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"QSpinBox:down-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-bottom-right-radius: 6;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"\n"
"}")
        self.spinBox_numPV.setObjectName("spinBox_numPV")
        self.btnAddKTP = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddKTP.setGeometry(QtCore.QRect(782, 230, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.btnAddKTP.setFont(font)
        self.btnAddKTP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddKTP.setStyleSheet("QPushButton{\n"
"    background-color:rgba(112, 215, 255, 0);\n"
"    color:rgba(0, 0, 0, 0.5);\n"
"    border: none;\n"
"    border-radius: 5;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"}\n"
"")
        self.btnAddKTP.setObjectName("btnAddKTP")
        self.spinBox_numKTP = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numKTP.setGeometry(QtCore.QRect(747, 230, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.spinBox_numKTP.setFont(font)
        self.spinBox_numKTP.setStyleSheet("QSpinBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QSpinBox:up-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-top-right-radius: 6;\n"
"}\n"
"QSpinBox:up-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-top-right-radius: 6;\n"
"    border: none;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"QSpinBox:down-button:hover{\n"
"    background-color:rgba(25,109,255, 0.7);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button:pressed{\n"
"    background-color:rgba(25,109,255, 0.5);\n"
"    border-bottom-right-radius: 6;\n"
"}\n"
"QSpinBox:down-button{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-bottom-right-radius: 6;\n"
"    border-left: 1px solid rgba(0,0,0,0.3);\n"
"\n"
"}")
        self.spinBox_numKTP.setObjectName("spinBox_numKTP")
        self.inputObjectType.raise_()
        self.inputTitleProject.raise_()
        self.listInvertor_folder.raise_()
        self.listInvertor_file.raise_()
        self.label_slide_title.raise_()
        self.checkBox_7.raise_()
        self.checkBox_5_1_1.raise_()
        self.btnShow3.raise_()
        self.checkBox_3_2.raise_()
        self.checkBox_4.raise_()
        self.btnShow8.raise_()
        self.checkBox_8_5.raise_()
        self.checkBox_5_1.raise_()
        self.checkBox_5_6.raise_()
        self.checkBox_6.raise_()
        self.checkBox_5.raise_()
        self.checkBox_5_1_2.raise_()
        self.btnShow5.raise_()
        self.checkBox_3_1.raise_()
        self.checkBox_3_3.raise_()
        self.checkBox_2.raise_()
        self.checkBox_5_3.raise_()
        self.checkBox_5_2.raise_()
        self.checkBox_5_1_4.raise_()
        self.checkBox_5_5.raise_()
        self.checkBox_1.raise_()
        self.checkBox_3_4.raise_()
        self.checkBox_8_3.raise_()
        self.checkBox_3.raise_()
        self.checkBox_5_4.raise_()
        self.checkBox_8.raise_()
        self.checkBox_8_4.raise_()
        self.checkBox_8_1.raise_()
        self.checkBox_8_2.raise_()
        self.checkBox_5_1_3.raise_()
        self.checkBox_8_6.raise_()
        self.label_3.raise_()
        self.inputCodeProject.raise_()
        self.label_6.raise_()
        self.label_for_slide.raise_()
        self.btnDrawScheme.raise_()
        self.btnFour.raise_()
        self.btnTwo.raise_()
        self.btnThree.raise_()
        self.textConsole.raise_()
        self.btnOne.raise_()
        self.label.raise_()
        self.btnForm.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.inputClient.raise_()
        self.listRoof.raise_()
        self.label_5.raise_()
        self.btnDevice.raise_()
        self.btnRP5.raise_()
        self.btnDrawSchemeTwo.raise_()
        self.btnSchemes.raise_()
        self.btnLoadScheme2.raise_()
        self.btnLoadScheme1.raise_()
        self.btnSlideMenu.raise_()
        self.btnOpenPDF.raise_()
        self.listPV_file.raise_()
        self.listPV_folder.raise_()
        self.listKTP_folder.raise_()
        self.listKTP_file.raise_()
        self.inputUDotIn.raise_()
        self.inputAddress.raise_()
        self.inputAddressLat.raise_()
        self.inputAddressLong.raise_()
        self.btnAddInvertor.raise_()
        self.spinBox_numInvertor.raise_()
        self.btnAddPV.raise_()
        self.spinBox_numPV.raise_()
        self.btnAddKTP.raise_()
        self.spinBox_numKTP.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto Report"))
        self.textConsole.setPlaceholderText(_translate("MainWindow", "Ход формирования файла "))
        self.btnTwo.setText(_translate("MainWindow", "Инвертор"))
        self.btnOne.setText(_translate("MainWindow", "PVsyst"))
        self.btnFour.setText(_translate("MainWindow", "Доп"))
        self.btnThree.setText(_translate("MainWindow", "Фэм"))
        self.label.setText(_translate("MainWindow", "Загрузка данных"))
        self.label_for_slide.setStyleSheet(_translate("MainWindow", "background-color: rgba(255,255,255,1); \n"
"border-radius: 5;\n"
"border: none;\n"
"padding: 2;"))
        self.label_for_slide.setText(_translate("MainWindow", "Оборудование"))
        self.btnForm.setText(_translate("MainWindow", "Сформировать PDF"))
        self.btnRP5.setText(_translate("MainWindow", "RP5"))
        self.btnDrawScheme.setText(_translate("MainWindow", "Схема №1"))
        self.btnDrawSchemeTwo.setText(_translate("MainWindow", "Схема №2"))
        self.inputTitleProject.setToolTip(_translate("MainWindow", "Количество MPPT в инверторе"))
        self.label_2.setText(_translate("MainWindow", "Инвертор"))
        self.label_4.setText(_translate("MainWindow", "КТП"))
        self.inputClient.setToolTip(_translate("MainWindow", "Количество MPPT в инверторе"))
        self.label_5.setText(_translate("MainWindow", "Тип крыши"))
        self.btnSchemes.setText(_translate("MainWindow", "Схемы"))
        self.btnDevice.setText(_translate("MainWindow", "Оборудование"))
        self.checkBox_8_1.setToolTip(_translate("MainWindow", "Отчет по выработке"))
        self.checkBox_8_1.setText(_translate("MainWindow", "8.1"))
        self.checkBox_8_2.setToolTip(_translate("MainWindow", "Структурная схема"))
        self.checkBox_8_2.setText(_translate("MainWindow", "8.2"))
        self.checkBox_8_4.setToolTip(_translate("MainWindow", "Схема постоянного тока"))
        self.checkBox_8_4.setText(_translate("MainWindow", "8.4"))
        self.checkBox_8_3.setToolTip(_translate("MainWindow", "Схема электрическая принципиальная"))
        self.checkBox_8_3.setText(_translate("MainWindow", "8.3"))
        self.checkBox_5_1_3.setToolTip(_translate("MainWindow", "Инверторное оборудование"))
        self.checkBox_5_1_3.setText(_translate("MainWindow", "5.1.3"))
        self.checkBox_3_1.setToolTip(_translate("MainWindow", "Описание границ участка"))
        self.checkBox_3_1.setText(_translate("MainWindow", "3.1"))
        self.checkBox_8_5.setToolTip(_translate("MainWindow", "План размещения"))
        self.checkBox_8_5.setText(_translate("MainWindow", "8.5"))
        self.checkBox_8_6.setToolTip(_translate("MainWindow", "Проект ТЗ на СЭС"))
        self.checkBox_8_6.setText(_translate("MainWindow", "8.6"))
        self.checkBox_5_3.setToolTip(_translate("MainWindow", "Электротехнические решения"))
        self.checkBox_5_3.setText(_translate("MainWindow", "5.3"))
        self.checkBox_5_4.setToolTip(_translate("MainWindow", "Система заземления и молниезащиты"))
        self.checkBox_5_4.setText(_translate("MainWindow", "5.4"))
        self.checkBox_5_5.setToolTip(_translate("MainWindow", "Выбор оптимальных показателей сравнение вариантов"))
        self.checkBox_5_5.setText(_translate("MainWindow", "5.5"))
        self.checkBox_3_3.setToolTip(_translate("MainWindow", "Топография площадки"))
        self.checkBox_3_3.setText(_translate("MainWindow", "3.3"))
        self.checkBox_5_6.setToolTip(_translate("MainWindow", "Индикативный анализ стоимости"))
        self.checkBox_5_6.setText(_translate("MainWindow", "5.6"))
        self.checkBox_5_1_2.setToolTip(_translate("MainWindow", "Опорные конструкции"))
        self.checkBox_5_1_2.setText(_translate("MainWindow", "5.1.2"))
        self.checkBox_5_1_4.setToolTip(_translate("MainWindow", "Другое силовое оборудование"))
        self.checkBox_5_1_4.setText(_translate("MainWindow", "5.1.4"))
        self.checkBox_5_2.setToolTip(_translate("MainWindow", "Планировочное решение"))
        self.checkBox_5_2.setText(_translate("MainWindow", "5.2"))
        self.checkBox_3_4.setToolTip(_translate("MainWindow", "Точка подключения объекта"))
        self.checkBox_3_4.setText(_translate("MainWindow", "3.4"))
        self.checkBox_3_2.setToolTip(_translate("MainWindow", "Климатические условия"))
        self.checkBox_3_2.setText(_translate("MainWindow", "3.2"))
        self.checkBox_5_1_1.setToolTip(_translate("MainWindow", "ФЭМ"))
        self.checkBox_5_1_1.setText(_translate("MainWindow", "5.1.1"))
        self.checkBox_5_1.setToolTip(_translate("MainWindow", "Назначение и состав СЭС"))
        self.checkBox_5_1.setText(_translate("MainWindow", "5.1"))
        self.btnLoadScheme2.setText(_translate("MainWindow", "▼"))
        self.btnLoadScheme1.setText(_translate("MainWindow", "▼"))
        self.inputCodeProject.setToolTip(_translate("MainWindow", "Код проекта"))
        self.label_3.setText(_translate("MainWindow", "ФЭМ"))
        self.btnSlideMenu.setToolTip(_translate("MainWindow", "Нажмите для перехода к другому меню"))
        self.btnSlideMenu.setText(_translate("MainWindow", "⮂"))
        self.btnShow3.setText(_translate("MainWindow", "▼"))
        self.btnShow5.setText(_translate("MainWindow", "▼"))
        self.btnShow8.setText(_translate("MainWindow", "▼"))
        self.label_slide_title.setText(_translate("MainWindow", "Номер раздела"))
        self.checkBox_7.setToolTip(_translate("MainWindow", "Перечень НТД"))
        self.checkBox_7.setText(_translate("MainWindow", "7"))
        self.checkBox_8.setToolTip(_translate("MainWindow", "Приложения:"))
        self.checkBox_8.setText(_translate("MainWindow", "8"))
        self.checkBox_2.setToolTip(_translate("MainWindow", "Исходные данные"))
        self.checkBox_2.setText(_translate("MainWindow", "2"))
        self.checkBox_4.setToolTip(_translate("MainWindow", "Анализ ресурсов (инсоляция)"))
        self.checkBox_4.setText(_translate("MainWindow", "4"))
        self.checkBox_5.setToolTip(_translate("MainWindow", "Основные параметры СЭС"))
        self.checkBox_5.setText(_translate("MainWindow", "5 "))
        self.checkBox_6.setToolTip(_translate("MainWindow", "Выводы и результаты"))
        self.checkBox_6.setText(_translate("MainWindow", "6"))
        self.checkBox_3.setToolTip(_translate("MainWindow", "Место размещения объекта"))
        self.checkBox_3.setText(_translate("MainWindow", "3"))
        self.checkBox_1.setToolTip(_translate("MainWindow", "Термины и сокращения"))
        self.checkBox_1.setText(_translate("MainWindow", "1"))
        self.btnOpenPDF.setText(_translate("MainWindow", "Открыть"))
        self.inputUDotIn.setToolTip(_translate("MainWindow", "Количество MPPT в инверторе"))
        self.inputAddress.setToolTip(_translate("MainWindow", "Количество MPPT в инверторе"))
        self.inputObjectType.setToolTip(_translate("MainWindow", "Количество MPPT в инверторе"))
        self.inputAddressLat.setToolTip(_translate("MainWindow", "Широта"))
        self.inputAddressLong.setToolTip(_translate("MainWindow", "Долгота"))
        self.btnAddInvertor.setToolTip(_translate("MainWindow", "Добавить MPPT"))
        self.btnAddInvertor.setText(_translate("MainWindow", "+"))
        self.btnAddPV.setToolTip(_translate("MainWindow", "Добавить MPPT"))
        self.btnAddPV.setText(_translate("MainWindow", "+"))
        self.btnAddKTP.setToolTip(_translate("MainWindow", "Добавить MPPT"))
        self.btnAddKTP.setText(_translate("MainWindow", "+"))
