# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/views/designCalcPV.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1349, 694)
        MainWindow.setBaseSize(QtCore.QSize(1622, 578))
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: white\n"
"}\n"
"QScrollBar:vertical {              \n"
"    background: #e5e5ea;\n"
"    border-radius: 3;\n"
"    border: none;\n"
"    max-width: 8px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #196dff;\n"
"    border-radius: 3;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #3b83ff; \n"
"    min-height: 0px;\n"
"    border-radius: 3;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: #e5e5ea;\n"
"    border: none;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background: transparent;\n"
"    border-radius: 6;\n"
"    border: none;\n"
"    outline:0px;\n"
"    selection-background-color: white;\n"
"    selection-color: #196dff;\n"
"    padding: 8 0 8 0;\n"
"}\n"
"")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #fff;")
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_stcnoct = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_stcnoct.setGeometry(QtCore.QRect(401, 70, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_stcnoct.setFont(font)
        self.comboBox_stcnoct.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_stcnoct.setStyleSheet("QComboBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border: none;\n"
"    border-radius: 6;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"")
        self.comboBox_stcnoct.setObjectName("comboBox_stcnoct")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(535, 130, 801, 511))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("background-color: #ffffff;\n"
"border-radius: 6;\n"
"border: none;\n"
"")
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.ActionMask)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(47)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignBottom)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(28, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(28, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(28, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(28, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(28, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(28, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(28, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(30, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(30, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(30, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(30, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(30, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(30, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(30, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(31, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(31, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(31, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(31, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(31, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(31, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(31, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(32, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(32, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(32, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(32, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(32, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(32, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(32, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(33, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(33, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(33, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(33, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(33, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(33, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(33, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(34, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(34, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(34, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(34, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(34, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(34, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(34, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(36, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(36, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(36, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(36, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(36, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(36, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(36, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(37, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(37, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(37, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(37, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(37, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(37, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(37, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(38, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(38, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(38, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(38, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(38, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(38, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(38, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(39, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(39, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(39, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(39, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(39, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(39, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(39, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(40, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(40, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(40, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(40, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(40, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(40, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(40, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(41, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(42, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(42, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(42, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(42, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(42, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(42, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(42, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(43, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(43, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(43, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(43, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(43, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(43, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(43, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(44, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(44, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(44, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(44, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(44, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(44, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(44, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(45, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(45, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(45, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(45, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(45, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(45, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(45, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(46, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(46, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(46, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(46, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(46, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(46, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(46, 6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(5)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.btnResult = QtWidgets.QPushButton(self.centralwidget)
        self.btnResult.setGeometry(QtCore.QRect(210, 600, 303, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.btnResult.setFont(font)
        self.btnResult.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnResult.setStyleSheet("QPushButton{\n"
"    background-color: rgb(60,178,0);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(60,178,0, 0.85); \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(255, 255, 255, 0.7);\n"
"    border-radius: 12;\n"
"}")
        self.btnResult.setCheckable(False)
        self.btnResult.setChecked(False)
        self.btnResult.setObjectName("btnResult")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(870, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSave.setFont(font)
        self.btnSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSave.setStyleSheet("QPushButton{\n"
"    background-color: rgba(229,229,234,1);\n"
"    color: #196dff;\n"
"    border: none;\n"
"    border-radius: 12;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #dceaff; \n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgba(25, 109, 255, 0.7); \n"
"    border-radius: 12;\n"
"}")
        self.btnSave.setObjectName("btnSave")
        self.comboBox_city = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_city.setGeometry(QtCore.QRect(202, 70, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_city.setFont(font)
        self.comboBox_city.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_city.setStyleSheet("QComboBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border: none;\n"
"    border-radius: 6;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"")
        self.comboBox_city.setEditable(False)
        self.comboBox_city.setMaxVisibleItems(10)
        self.comboBox_city.setIconSize(QtCore.QSize(10, 20))
        self.comboBox_city.setFrame(True)
        self.comboBox_city.setProperty("placeholderText", "")
        self.comboBox_city.setObjectName("comboBox_city")
        self.listPV_file = QtWidgets.QComboBox(self.centralwidget)
        self.listPV_file.setGeometry(QtCore.QRect(302, 20, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.listPV_file.setFont(font)
        self.listPV_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listPV_file.setStyleSheet("QComboBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border: none;\n"
"    border-radius: 6;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"")
        self.listPV_file.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listPV_file.setEditable(False)
        self.listPV_file.setCurrentText("")
        self.listPV_file.setProperty("placeholderText", "")
        self.listPV_file.setObjectName("listPV_file")
        self.listPV_folder = QtWidgets.QComboBox(self.centralwidget)
        self.listPV_folder.setGeometry(QtCore.QRect(202, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.listPV_folder.setFont(font)
        self.listPV_folder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listPV_folder.setStyleSheet("QComboBox{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border: none;\n"
"    border-radius: 6;\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QComboBox:drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"")
        self.listPV_folder.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listPV_folder.setEditable(False)
        self.listPV_folder.setCurrentText("")
        self.listPV_folder.setProperty("placeholderText", "")
        self.listPV_folder.setObjectName("listPV_folder")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 81, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 70, 171, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgba(255,255,255,0); ")
        self.label_11.setScaledContents(False)
        self.label_11.setObjectName("label_11")
        self.lineEdit_pnom = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pnom.setGeometry(QtCore.QRect(110, 148, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_pnom.setFont(font)
        self.lineEdit_pnom.setAutoFillBackground(False)
        self.lineEdit_pnom.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_pnom.setText("")
        self.lineEdit_pnom.setReadOnly(False)
        self.lineEdit_pnom.setObjectName("lineEdit_pnom")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(21, 159, 42, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(21, 203, 20, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(21, 254, 25, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_isc = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_isc.setGeometry(QtCore.QRect(110, 198, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_isc.setFont(font)
        self.lineEdit_isc.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_isc.setReadOnly(False)
        self.lineEdit_isc.setObjectName("lineEdit_isc")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(21, 305, 25, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_9.setObjectName("label_9")
        self.lineEdit_voc = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_voc.setGeometry(QtCore.QRect(110, 248, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_voc.setFont(font)
        self.lineEdit_voc.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_voc.setReadOnly(False)
        self.lineEdit_voc.setObjectName("lineEdit_voc")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(21, 358, 30, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_12.setObjectName("label_12")
        self.lineEdit_imp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_imp.setGeometry(QtCore.QRect(110, 299, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_imp.setFont(font)
        self.lineEdit_imp.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_imp.setReadOnly(False)
        self.lineEdit_imp.setObjectName("lineEdit_imp")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(21, 407, 46, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_vmp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_vmp.setGeometry(QtCore.QRect(110, 348, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vmp.setFont(font)
        self.lineEdit_vmp.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_vmp.setReadOnly(False)
        self.lineEdit_vmp.setObjectName("lineEdit_vmp")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(21, 458, 82, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_muisc = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_muisc.setGeometry(QtCore.QRect(110, 397, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_muisc.setFont(font)
        self.lineEdit_muisc.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_muisc.setReadOnly(False)
        self.lineEdit_muisc.setObjectName("lineEdit_muisc")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(21, 508, 63, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_7.setObjectName("label_7")
        self.lineEdit_muvocspec = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_muvocspec.setGeometry(QtCore.QRect(110, 447, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_muvocspec.setFont(font)
        self.lineEdit_muvocspec.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_muvocspec.setReadOnly(False)
        self.lineEdit_muvocspec.setObjectName("lineEdit_muvocspec")
        self.lineEdit_vmaxiec = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_vmaxiec.setGeometry(QtCore.QRect(110, 497, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vmaxiec.setFont(font)
        self.lineEdit_vmaxiec.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_vmaxiec.setReadOnly(False)
        self.lineEdit_vmaxiec.setObjectName("lineEdit_vmaxiec")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(21, 558, 53, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_10.setObjectName("label_10")
        self.lineEdit_rshunt = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rshunt.setGeometry(QtCore.QRect(110, 548, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_rshunt.setFont(font)
        self.lineEdit_rshunt.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_rshunt.setReadOnly(False)
        self.lineEdit_rshunt.setObjectName("lineEdit_rshunt")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(21, 612, 45, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_13.setObjectName("label_13")
        self.lineEdit_ncels = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ncels.setGeometry(QtCore.QRect(110, 600, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_ncels.setFont(font)
        self.lineEdit_ncels.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_ncels.setReadOnly(False)
        self.lineEdit_ncels.setObjectName("lineEdit_ncels")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(212, 348, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_23.setObjectName("label_23")
        self.lineEdit_calcmaxtemp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_calcmaxtemp.setGeometry(QtCore.QRect(430, 198, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_calcmaxtemp.setFont(font)
        self.lineEdit_calcmaxtemp.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_calcmaxtemp.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_calcmaxtemp.setText("")
        self.lineEdit_calcmaxtemp.setPlaceholderText("")
        self.lineEdit_calcmaxtemp.setClearButtonEnabled(False)
        self.lineEdit_calcmaxtemp.setObjectName("lineEdit_calcmaxtemp")
        self.lineEdit_irradiance = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_irradiance.setGeometry(QtCore.QRect(430, 497, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_irradiance.setFont(font)
        self.lineEdit_irradiance.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_irradiance.setPlaceholderText("")
        self.lineEdit_irradiance.setObjectName("lineEdit_irradiance")
        self.lineEdit_noct = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_noct.setGeometry(QtCore.QRect(430, 548, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_noct.setFont(font)
        self.lineEdit_noct.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_noct.setPlaceholderText("")
        self.lineEdit_noct.setObjectName("lineEdit_noct")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(212, 256, 166, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_21.setObjectName("label_21")
        self.lineEdit_countfem = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_countfem.setGeometry(QtCore.QRect(430, 397, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_countfem.setFont(font)
        self.lineEdit_countfem.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_countfem.setPlaceholderText("")
        self.lineEdit_countfem.setObjectName("lineEdit_countfem")
        self.lineEdit_umax_pogran = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_umax_pogran.setGeometry(QtCore.QRect(780, 70, 73, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_umax_pogran.setFont(font)
        self.lineEdit_umax_pogran.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_umax_pogran.setAutoFillBackground(False)
        self.lineEdit_umax_pogran.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_umax_pogran.setText("")
        self.lineEdit_umax_pogran.setReadOnly(False)
        self.lineEdit_umax_pogran.setObjectName("lineEdit_umax_pogran")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(212, 508, 125, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_26.setObjectName("label_26")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(662, 62, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_16.setObjectName("label_16")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(212, 448, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_25.setObjectName("label_25")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(212, 147, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_19.setObjectName("label_19")
        self.lineEdit_calcmintemp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_calcmintemp.setGeometry(QtCore.QRect(430, 148, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_calcmintemp.setFont(font)
        self.lineEdit_calcmintemp.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_calcmintemp.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_calcmintemp.setText("")
        self.lineEdit_calcmintemp.setPlaceholderText("")
        self.lineEdit_calcmintemp.setClearButtonEnabled(False)
        self.lineEdit_calcmintemp.setObjectName("lineEdit_calcmintemp")
        self.lineEdit_max = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_max.setGeometry(QtCore.QRect(430, 299, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_max.setFont(font)
        self.lineEdit_max.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_max.setPlaceholderText("")
        self.lineEdit_max.setObjectName("lineEdit_max")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(212, 305, 172, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(212, 404, 168, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_24.setObjectName("label_24")
        self.lineEdit_mintemp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mintemp.setGeometry(QtCore.QRect(430, 348, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_mintemp.setFont(font)
        self.lineEdit_mintemp.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_mintemp.setPlaceholderText("")
        self.lineEdit_mintemp.setObjectName("lineEdit_mintemp")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(212, 198, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_20.setObjectName("label_20")
        self.lineEdit_countparallel = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_countparallel.setGeometry(QtCore.QRect(430, 447, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_countparallel.setFont(font)
        self.lineEdit_countparallel.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_countparallel.setPlaceholderText("")
        self.lineEdit_countparallel.setObjectName("lineEdit_countparallel")
        self.lineEdit_min = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_min.setGeometry(QtCore.QRect(430, 248, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_min.setFont(font)
        self.lineEdit_min.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_min.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_min.setText("")
        self.lineEdit_min.setPlaceholderText("")
        self.lineEdit_min.setClearButtonEnabled(False)
        self.lineEdit_min.setObjectName("lineEdit_min")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(662, 17, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_14.setObjectName("label_14")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(212, 556, 44, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_27.setObjectName("label_27")
        self.lineEdit_imax_pogran = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_imax_pogran.setGeometry(QtCore.QRect(780, 20, 73, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_imax_pogran.setFont(font)
        self.lineEdit_imax_pogran.setAutoFillBackground(False)
        self.lineEdit_imax_pogran.setStyleSheet("QLineEdit{\n"
"    background-color:rgba(229,229,234,1); \n"
"    border-radius: 6;\n"
"    border: none;\n"
"    padding-left: 8px\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color:rgba(242,242,247,1);\n"
"}\n"
"QLineEdit:pressed{\n"
"    background-color:rgba(188,188,192,1);\n"
"    border-radius: 12;\n"
"}")
        self.lineEdit_imax_pogran.setText("")
        self.lineEdit_imax_pogran.setReadOnly(False)
        self.lineEdit_imax_pogran.setObjectName("lineEdit_imax_pogran")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(530, 40, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color:rgba(209,209,214,0.01);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.lineEdit_pnom.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_isc.raise_()
        self.label_9.raise_()
        self.lineEdit_voc.raise_()
        self.label_12.raise_()
        self.lineEdit_imp.raise_()
        self.label_4.raise_()
        self.lineEdit_vmp.raise_()
        self.label_5.raise_()
        self.lineEdit_muisc.raise_()
        self.label_7.raise_()
        self.lineEdit_muvocspec.raise_()
        self.lineEdit_vmaxiec.raise_()
        self.label_10.raise_()
        self.lineEdit_rshunt.raise_()
        self.label_13.raise_()
        self.lineEdit_ncels.raise_()
        self.label_23.raise_()
        self.lineEdit_calcmaxtemp.raise_()
        self.lineEdit_irradiance.raise_()
        self.lineEdit_noct.raise_()
        self.label_21.raise_()
        self.lineEdit_countfem.raise_()
        self.lineEdit_umax_pogran.raise_()
        self.label_26.raise_()
        self.label_16.raise_()
        self.label_25.raise_()
        self.label_19.raise_()
        self.lineEdit_calcmintemp.raise_()
        self.lineEdit_max.raise_()
        self.label_22.raise_()
        self.label_24.raise_()
        self.lineEdit_mintemp.raise_()
        self.label_20.raise_()
        self.lineEdit_countparallel.raise_()
        self.lineEdit_min.raise_()
        self.label_14.raise_()
        self.label_27.raise_()
        self.lineEdit_imax_pogran.raise_()
        self.label_15.raise_()
        self.comboBox_stcnoct.raise_()
        self.tableWidget.raise_()
        self.btnResult.raise_()
        self.btnSave.raise_()
        self.comboBox_city.raise_()
        self.listPV_file.raise_()
        self.listPV_folder.raise_()
        self.label_6.raise_()
        self.label_11.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CalcPV"))
        self.comboBox_stcnoct.setToolTip(_translate("MainWindow", "Условие расчета"))
        self.comboBox_stcnoct.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Выьор режима</p></body></html>"))
        self.tableWidget.setToolTip(_translate("MainWindow", "*Первая цифра № метода расчета I, вторая цифра № метода расчета V"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1-1"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "1-3"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "1-4"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "1-5"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "2-1"))
        item = self.tableWidget.verticalHeaderItem(30)
        item.setText(_translate("MainWindow", "2-3"))
        item = self.tableWidget.verticalHeaderItem(36)
        item.setText(_translate("MainWindow", "2-4"))
        item = self.tableWidget.verticalHeaderItem(42)
        item.setText(_translate("MainWindow", "2-5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ток, А"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Напряжение, В"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Мощность, Вт"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Температура, \'C"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "T"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Напряжение ФЭМ"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Суммарный ток пар. цеп."))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "Расч. мин."))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "Расч. макс."))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "Абс. мин."))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "Абс. макс."))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("MainWindow", "Мин. темп."))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("MainWindow", "Расч. мин."))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("MainWindow", "Расч. макс."))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("MainWindow", "Абс. мин."))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("MainWindow", "Абс. макс."))
        item = self.tableWidget.item(10, 4)
        item.setText(_translate("MainWindow", "Мин. темп."))
        item = self.tableWidget.item(12, 4)
        item.setText(_translate("MainWindow", "Расч. мин."))
        item = self.tableWidget.item(13, 4)
        item.setText(_translate("MainWindow", "Расч. макс."))
        item = self.tableWidget.item(14, 4)
        item.setText(_translate("MainWindow", "Абс. мин."))
        item = self.tableWidget.item(15, 4)
        item.setText(_translate("MainWindow", "Абс. макс."))
        item = self.tableWidget.item(16, 4)
        item.setText(_translate("MainWindow", "Мин. темп."))
        item = self.tableWidget.item(18, 4)
        item.setText(_translate("MainWindow", "Расч. мин."))
        item = self.tableWidget.item(19, 4)
        item.setText(_translate("MainWindow", "Расч. макс."))
        item = self.tableWidget.item(20, 4)
        item.setText(_translate("MainWindow", "Абс. мин."))
        item = self.tableWidget.item(21, 4)
        item.setText(_translate("MainWindow", "Абс. макс."))
        item = self.tableWidget.item(22, 4)
        item.setText(_translate("MainWindow", "Мин. темп."))
        item = self.tableWidget.item(24, 4)
        item.setText(_translate("MainWindow", "Расч. мин."))
        item = self.tableWidget.item(25, 4)
        item.setText(_translate("MainWindow", "Расч. макс."))
        item = self.tableWidget.item(26, 4)
        item.setText(_translate("MainWindow", "Абс. мин."))
        item = self.tableWidget.item(27, 4)
        item.setText(_translate("MainWindow", "Абс. макс."))
        item = self.tableWidget.item(28, 4)
        item.setText(_translate("MainWindow", "Мин. темп."))
        item = self.tableWidget.item(30, 4)
        item.setText(_translate("MainWindow", "Расч. мин."))
        item = self.tableWidget.item(31, 4)
        item.setText(_translate("MainWindow", "Расч. макс."))
        item = self.tableWidget.item(32, 4)
        item.setText(_translate("MainWindow", "Абс. мин."))
        item = self.tableWidget.item(33, 4)
        item.setText(_translate("MainWindow", "Абс. макс."))
        item = self.tableWidget.item(34, 4)
        item.setText(_translate("MainWindow", "Мин. темп."))
        item = self.tableWidget.item(36, 4)
        item.setText(_translate("MainWindow", "Расч. мин."))
        item = self.tableWidget.item(37, 4)
        item.setText(_translate("MainWindow", "Расч. макс."))
        item = self.tableWidget.item(38, 4)
        item.setText(_translate("MainWindow", "Абс. мин."))
        item = self.tableWidget.item(39, 4)
        item.setText(_translate("MainWindow", "Абс. макс."))
        item = self.tableWidget.item(40, 4)
        item.setText(_translate("MainWindow", "Мин. темп."))
        item = self.tableWidget.item(42, 4)
        item.setText(_translate("MainWindow", "Расч. мин."))
        item = self.tableWidget.item(43, 4)
        item.setText(_translate("MainWindow", "Расч. макс."))
        item = self.tableWidget.item(44, 4)
        item.setText(_translate("MainWindow", "Абс. мин."))
        item = self.tableWidget.item(45, 4)
        item.setText(_translate("MainWindow", "Абс. макс."))
        item = self.tableWidget.item(46, 4)
        item.setText(_translate("MainWindow", "Мин. темп."))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.btnResult.setText(_translate("MainWindow", "Рассчитать"))
        self.btnSave.setToolTip(_translate("MainWindow", "Сохранение таблицы с результатами в xls"))
        self.btnSave.setText(_translate("MainWindow", "Сохранить в xls"))
        self.comboBox_city.setToolTip(_translate("MainWindow", "Город"))
        self.listPV_file.setToolTip(_translate("MainWindow", "Модель"))
        self.listPV_folder.setToolTip(_translate("MainWindow", "Фирма"))
        self.label_6.setText(_translate("MainWindow", "ФЭМ:"))
        self.label_11.setText(_translate("MainWindow", "Температура города:\n"
"Условие расчета: "))
        self.label.setText(_translate("MainWindow", "PNom"))
        self.label_2.setText(_translate("MainWindow", "Isc"))
        self.label_3.setText(_translate("MainWindow", "Voc"))
        self.label_9.setText(_translate("MainWindow", "Imp"))
        self.label_12.setText(_translate("MainWindow", "Vmp"))
        self.label_4.setText(_translate("MainWindow", "muISC"))
        self.label_5.setText(_translate("MainWindow", "muVocSpec"))
        self.label_7.setText(_translate("MainWindow", "VMaxIEC"))
        self.label_10.setText(_translate("MainWindow", "RShunt"))
        self.label_13.setText(_translate("MainWindow", "NCelS"))
        self.label_23.setText(_translate("MainWindow", "Минимальная температура \n"
"(0.98)"))
        self.label_21.setToolTip(_translate("MainWindow", "(Импортируется с RP5)"))
        self.label_21.setText(_translate("MainWindow", "Абсолютный минимум"))
        self.label_26.setText(_translate("MainWindow", "Инсоляция, В/м2"))
        self.label_16.setText(_translate("MainWindow", "Umax \n"
"инвертора"))
        self.label_25.setText(_translate("MainWindow", "Число параллельных \n"
"цепочек"))
        self.label_19.setText(_translate("MainWindow", "Расчетная минимальная \n"
"температура"))
        self.label_22.setToolTip(_translate("MainWindow", "(Импортируется с RP5)"))
        self.label_22.setText(_translate("MainWindow", "Абсолютный максимум"))
        self.label_24.setText(_translate("MainWindow", "Число ФЭМ в цепочке"))
        self.label_20.setText(_translate("MainWindow", "Расчетная максимальная \n"
"температура"))
        self.label_14.setText(_translate("MainWindow", "Imax на \n"
"один МРРТ"))
        self.label_27.setText(_translate("MainWindow", "NOCT"))
        self.label_15.setText(_translate("MainWindow", "Пограничные \n"
"значения:"))
